### ISSUE TITLE
Degree Planner Fix

### ISSUE THREAD

**Issue by mercedezcastro** [radgrad/radgrad2#120]
Please do work for this task in a branch called issue-120.

Unable to move and remove courses in degree planner (drag and drop).

Related to #42 

* [x] Clicking on a course doesn't update the details tab.
* [x] Clicking remove on details tab should change the tab.
* [x] Can drag classes into the past. This shouldn't be possible.

**Comment by cammoore** [comment]
I'm going to use this issue to fix the degree planner.

* [ ] Clicking on a course doesn't update the details course.

**Comment by cammoore** [comment]
The reducer for clicking on courses and opportunities was wrong. It wasn't updating the right part of the state.

**Comment by cammoore** [comment]
Clicking remove in the details does remove but we should switch the tab back to something else.
