### ISSUE TITLE
Website for profiles being null causes problems with forms

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#123]
Please do work for this task in a branch called issue-123.

If you look at our semester fixture, some profiles (for all roles) have their websites as *null*. This causes some problems when working with Uniforms in that it does not like the value of something being null.

This can be easily fixed by changing the websites to be empty strings (`""`). But we should also probably handle this internally in our profile collections if needed.

**Comment by cammoore** [comment]
Replaced the nulls in profiles with "". Need to do meteor reset to reload the profiles.
