### ISSUE TITLE
Switch meteor packages lodash and moment to their npm counterparts

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#129]
Please do work for this task in a branch called issue-129.

Need to switch from `import { _ } from meteor/erasaur:meteor-lodash` to `import * as _ from lodash`and `import { moment } from 'meteor/momentjs:moment'` to `import * as moment from 'moment'`

* The erasaur lodash wrapper is deprecated and some new lodash functions does not exist in this meteor atmosphere package.
* Another reason for switching both these package is that we get the added benefit of the typings (@types/lodash and moment has built-in types into it). This should boost developer productivity (smarter autocomplete) and reduce errors (typing the a method the wrong way or incorrectly using the functions).

**Comment by cammoore** [comment]
left one instance of the Meteor lodash package. Changing it caused a TS error.
