### ISSUE TITLE
Get Analytics Working.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#146]
Please do work for this task in a branch called issue-146.

We need to ensure that the Analytics pages are working properly.

* [x] Logged In Users
* [x] Newsletter
* [x] Overhead analysis
* [x] Student summary
* [x] User Interactions

**Comment by cammoore** [comment]
Need to fix student summary so it uses Redux.

**Comment by cammoore** [comment]
Need to do the timeline chart for student summary.

**Comment by gcalica** [comment]
This is the current status of Newsletter according to Quinne:
<img width="633" alt="Screen Shot 2020-05-26 at 6 08 59 PM" src="https://user-images.githubusercontent.com/25701594/82976878-fd702380-9f7b-11ea-9f71-e6ef630a6595.png">

**Comment by cammoore** [comment]
I'll take on the Newsletter. Should I use this branch or another?

**Comment by gcalica** [comment]
You can use this branch. I wasn't really planning on working on this issue until after I went through some of the pages for any UI bugs and after I complete my research proposal implementation which should be (hopefully) a week or two.

**Comment by cammoore** [comment]
Do we need the setTimeout to slow the sending of the emails?
