### ISSUE TITLE
Allow students to opt-in to have their card appear on the landing page. 

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#148]
Please do work for this task in a branch called issue-148.

The current landing page has four cards representing students. The data is fake.

* [ ] Update the Student About Me page to allow the students to opt in to having their card appear on the landing page. 

* [ ] Update the StudentProfile collection to hold the students' choice.

* [ ] Update the Landing page to randomly choose four students who have opted in and display their cards.

**Comment by gcalica** [comment]
Related to #221 
The landing page has been re-designed to instead use an animated GIF (which are all still 4 fake data profiles). 
@hannaparkUH Do we plan on keeping the animated GIF or replace that with this issue?

**Comment by hannaparkUH** [comment]
@gcalica I think we should keep the animated GIF on the landing page.

**Comment by gcalica** [comment]
With the re-design of RadGrad2 having an animated GIF in place of the landing page cards, this issue is no longer relevant.
