### ISSUE TITLE
Update screenshots used in the Guided tours.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#149]
Please do work for this task in a branch called issue-149.

The interface has changed, we need to update the screenshots for the guided tours.

**Comment by gcalica** [comment]
For the Student Guided tour of the Sample Student section, when updating the old screenshot: we need to either change the sample student degree planner to match the paragraph description or change the paragraph description to match the screenshot.

**Comment by gcalica** [comment]
@hannaparkUH Related to #221

**Comment by cammoore** [comment]
We removed the guided tours.
