### ISSUE TITLE
What are we going to do about Feeds?

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#172]
Please do work for this task in a branch called issue-172.

The original idea behind Feeds was good and we ran into FERPA issues with displaying student names.

The Feeds collection is very complicated. It needs a redesign. 

Do we need Feeds any more?

**Comment by philipmjohnson** [comment]
Yes, I think Feeds provides an important service to users. Without it, they will have no idea what is happening in the system and what other users are accomplishing. 

I am heartily in favor of a redesign, but let's keep the basic idea alive.

**Comment by gcalica** [comment]
Related to #221 
@hannaparkUH

**Comment by hannaparkUH** [comment]
Why don't we move the Feeds to the Users Page (Under Community)?
