### ISSUE TITLE
Update HelpMessages Screenshots

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#183]
Please do work for this task in a branch called issue-183.

Update the screenshots used in HelpMessages. And fix the text for the HelpMessages accordingly such that they match what is shown in the screenshot.

**Comment by gcalica** [comment]
@hannaparkUH In the re-design of RadGrad, do you plan on having screenshots for the Help Messages? If not, feel free to close this issue.

**Comment by hannaparkUH** [comment]
@gcalica I have modified the help messages for student pages. I will let you know after I finish updating the help messages for the faculty, mentor and advisor.

**Comment by cammoore** [comment]
We removed help messages.
