### ISSUE TITLE
MenuIceCircle Stats

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#196]
Please do work for this task in a branch called issue-196.

RadGrad1 has the ICE Circles of the top menu function such that when you hover over it, it shows in a popup your "Earned/Projected" score for the corresponding ICE Circle. RadGrad2 does not.

RadGrad1 also has the ICE Circles display the total earned points, even if it goes over 100 points. RadGrad2 caps at 100 points.

**Comment by cammoore** [comment]
In RadGrad1 we show values over 100. Do we want to do this in RadGrad2?
