### ISSUE TITLE
withSubscriptions HOC

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#2]
Please do work for this task in a branch called issue-2.

Want to create with*Subscriptions Higher order Components to manage the subscriptions.
- [ ] Public Stats: for the landing page and guided tours.
- [ ] Global: similar to the RadGrad1 WithGlobalSubscriptions template.
- [ ] Advisor: similar to the WithAdvisorSubscriptions
- [ ] Instance: similar to the WithInstanceSubscriptions

**Comment by cammoore** [comment]
Need to talk about this one. Not sure how to make this work. Even getting something as simple as Public Stats working is difficult.

**Comment by philipmjohnson** [comment]
I came across this today:

https://reactjs.org/docs/hooks-intro.html

Maybe hooks are a more simple way to do it?

**Comment by cammoore** [comment]
I finally wrapped my head around this. There are now 3 HOC dealing with subscriptions:

* withGenericSubscriptions takes a Component and an array of Publication names. Will render the Component after all the subscriptions are ready.
* withGlobalSubscriptions takes a Component and subscribes to the Global subscriptions.
* withInstanceSubscriptions takes a Component and subscribes to the Instance subscriptions.
The public stats subscription is just a withGenericSubscriptions with the PublicStats.getPublicationName().
The old WithAdvisorSubscriptions become withGenericSubscriptions with PlanChoices.getPublicationName().
