### ISSUE TITLE
[object Object] Console Error

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#203]
Please do work for this task in a branch called issue-203.

![Screen Shot 2020-05-29 at 10 10 46 PM](https://user-images.githubusercontent.com/25701594/83323272-4680db80-a1f9-11ea-96c4-dd5367d50861.png)

Getting this error from any new and recent branches made. Appears right after the `=> App running at: http://localhost:3200/` message when booting up localhost. Also only appears for the initial bootup after doing a `meteor reset`. At least from what I've noticed, it doesn't really break anything while I'm developing and looking through the web app.

**Comment by gcalica** [comment]
Don't really seem to be getting this anymore with branches that are up-to-date with master. Closing this if I continue to not get these errors anymore for a few weeks.

**Comment by cammoore** [comment]
The [object Object] is part of the console.trace call. I commented it out.

**Comment by gcalica** [comment]
As discussed in a previous meeting, we believe this error might be related to #224

**Comment by cammoore** [comment]
I changed the publication code from if (!studentID) to if (_.isNil(studentID)). I think this should solve the problem

Going to close this issue and reopen if we see the stack traces.
