### ISSUE TITLE
"Groups" for AcademicPlans

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#206]
Please do work for this task in a branch called issue-206.

![Screen Shot 2020-05-29 at 11 18 00 PM](https://user-images.githubusercontent.com/25701594/83325725-4c32ed00-a20a-11ea-8c2f-923b75a998fe.png)

In `AcademicPlanStaticYearView.tsx` file, we supply the `<AcademicPlanStaticTermView>` with a prop called groups and supply the following value `groups={props.academicPlan.groups}` with `academicPlan` being of type `IAcademicPlan` as shown in the image above.

Inside the `AcademicPlanStaticTermView.tsx` file, we use this `groups` props as such:
![Screen Shot 2020-05-30 at 12 14 53 AM](https://user-images.githubusercontent.com/25701594/83325762-a2a02b80-a20a-11ea-843c-16060befd3f2.png)

`isPlanChoiceSatisfied()` is a function that currently only takes 2 arguments but right now it's being supplied the third argument which is `groups`.

We supply `<SatisfiedPlanChoicePill>` with the prop `groups` but inside that file we don't actually use it or even have it declared as a prop in the interface for that file.

Need to determine if this `groups` prop is something we still need or something that is no longer used and just forgotten to be removed.

**Comment by gcalica** [comment]
@cammoore Don't really have much idea of how the whole AcademicPlan stuff works in RadGrad2, so I'm not sure if the `groups` prop is something needed or something that was just forgotten to be removed.

**Comment by cammoore** [comment]
@gcalica The idea of groups was an array of course slugs that would satisfy the plan choice requirement. I started down the path of having the groups field when I tried to implement the Data Science track. They have a data science elective. Unfortunately, no one could tell me the list of courses that satisfy the elective. So, I dropped the concept. We may need to revisit this later.

**Comment by cammoore** [comment]
Removed groups from the viewer. We should revisit this idea later.
