### ISSUE TITLE
Course & Opportunity Reviews Bugs

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#210]
Please do work for this task in a branch called issue-210.

Bug 1 (UI):
When editing a review, the default value of "Academic Term" field should be the current review's academic term.

Bug 2 (UI):
When first adding a review, the default option value displayed for the "Rating" field should be the default rating (3).

Bug 3 (UI):
After updating a review, the "Academic Term" field defaults back to the first Academic Term option rather than the new and updated Academic Term.

Bug 4:
![Screen Shot 2020-05-31 at 10 23 18 PM](https://user-images.githubusercontent.com/25701594/83390333-5a5d4680-a38d-11ea-938a-f6e9827ae37c.png)
![Screen Shot 2020-05-31 at 10 30 16 PM](https://user-images.githubusercontent.com/25701594/83390926-6d244b00-a38e-11ea-8615-5a271f5604c7.png)

**Comment by cammoore** [comment]
* [ ] Bug 1, cannot reproduce. The academic term is set correctly when there is only one choice.
* [x] Bug 2, done.
* [x] Bug 3, done, and can't review unverified opportunities.
* [ ] Bug 4, I think this is an issue in Autoforms. Can't fix right now.
