### ISSUE TITLE
Redesign RadGrad2 - Landing page and Student pages

### ISSUE THREAD

**Issue by hannaparkUH** [radgrad/radgrad2#221]
Please do work for this task in a branch called issue-221.

Update the design layouts of RadGrad2.

- [x] Homepage
- [x] Student Home Page
- [x] Academic Plans
- [x] Career Goals
- [x] Courses
- [x] Interests
- [x] Opportunities
- [ ] Degree Planner
- [x] Users
- [x] RadGrad Videos
- [x] About me
- [x] ICE Points
- [x] Levels
- [x] Advisor Log

**Comment by hannaparkUH** [comment]
@gcalica 
- [ ] RadGrad video - add the short descriptions to each video.
- [ ] Student homepage -  "Learn More" buttons link to "opportunities", "courses" and "careers"

**Comment by gcalica** [comment]
New components and their functionality proposed by this redesign have now been all implemented. They also have decent UI changes now, with only a little bit more polishing needed to meet the specs of the figma mockup. Closing this issue and will instead make separate issues for each page that needs their UI polished.
