### ISSUE TITLE
Remove careerGoalIDs, interestIDs, and academicPlanID instances from the codebase

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#234]
Please do work for this task in a branch called issue-234.

With the now usage of Favorites, these fields from a student profile are no longer necessary. Remove these instances from our codebase.

Things to work on in this issue:
<del>* Since students can now have more than one academic plan favorited, how do we provide students feedback about how close they are to graduation based on their favorited academic plans? Or what recommended courses they should take?</del> Academic Plans soon to be deprecated.
<del>* We mainly used careerGoalIDs and interestIDs as a way to find recommendations for students. Need to re-code any functionality related to this to instead use favorites.
</del> Already implemented.
* From the Admin Analytics side, a student updating their career goals/interests/academic plans is categorized under "Change Outlook". Need to re-code the Student Summary so that we're instead gonna check for add, update, and remove course and opportunity and from there check if it is a career goal/interest/academic plan that they changed which would then be categorized under the "Change Outlook".

**Comment by cammoore** [comment]
We need to update how the analytics system works.
