### ISSUE TITLE
Revisit the idea of academic plan choices and how to know if they are satisfied.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#237]
Please do work for this task in a branch called issue-XXX.

Academic plans have PlanChoices. PlanChoices allow students to take a course that satisfies them. Some examples of PlanChoices are:

* ICS 211
* ICS 312 or ICS 331
* (ICS 312 or ICS 331) or (ICS 313 or ICS 361) or (ICS 351 or ICS 451) or ICS 355
* ICS 400+
* Data science 400+

All of the above choices except for the last are relatively easy to check if they are satisfied. Has the student taken a course in the PlanChoice? The last one is very difficult to determine if the student has satisfied the PlanChoice.

One idea to solve this is to add an object tentatively called groups to the PlanChoice. The groups object could have a label for rendering the PlanChoice, a list of course slugs that satisfy the PlanChoice, and maybe a function to determine if a course satisfies the PlanChoice.

This will require an update to the fixtures.

**Comment by cammoore** [comment]
Related to #266.

**Comment by philipmjohnson** [comment]
No longer important since we will remove academic plans.
