### ISSUE TITLE
Do performance analysis and assess runtime responsiveness

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#249]
Please do work for this task in a branch called issue-249.

We need to figure out where RadGrad2 is spending it's time and hopefully improve the performance.

  * Ensure that appropriate indexes are being defined on all collections
  * Create a "realistic" dataset for RadGrad2 by importing a RadGrad1 snapshot.
  * Login as a student in developer mode. Use Monti APM to see where time is being spent.

**Comment by philipmjohnson** [comment]
On 1/27/21, I did a quick walkthrough of the opq user on radgrad2.ics.hawaii.edu (version 2.0.8).  This instance had a snapshot of RadGrad1 loaded so the database was realistic.

Landing page display time: 2 seconds.
Upon providing credentials, time to display home page: 3 seconds
All other pages (except for Interests page) displayed in under a second.
The interests page took about 3 seconds to display.

I looked at the Monti APM dashboard and all of the measurements there seemed nominal. 

I am going to close this issue for now as the performance of radgrad2 for students seems reasonable.
