### ISSUE TITLE
Add a property to settings.development.json and settings.production.json to turn off Mentor Space.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#258]
Please do work for this task in a branch called issue-258.

We should have a property in the settings file to turn on/off Mentor Space. It isn't used right now and we haven't engaged the Mentors. 

We'll use this setting to not load the menu items to send the user to the mentor space.  We won't remove the pages or the routes, just make it difficult to get to the pages if you don't know the URL.

**Comment by philipmjohnson** [comment]
Closing this issue since we're removing MentorSpace altogether.
