### ISSUE TITLE
Address the TODOs in the code.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#263]
Please do work for this task in a branch called issue-263.

We have 30 TODO/FIXME items in RadGrad2. We need to check them out and either:

  * Make an issue specifying how to resolve them.
  * Make a comment indicating that they are technical debt.

**Comment by philipmjohnson** [comment]
I went through all of the TODOs and basically all of them are "technical debt". I didn't see much that warranted an explicit Issue.  Therefore, I think it's best to just think to ourselves that "TODO" is a synonym for technical debt and leave it at that.  The good thing about TODO is that IntelliJ makes it a different color, so it's a "special" kind of comment. 

I am closing this issue as basically a "won't fix" situation.
