### ISSUE TITLE
Remove academic plans

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#266]
Please do work for this task in a branch called issue-266.

Academic Plans were an interesting idea but have proven too unwieldy and should be removed for RadGrad2.

There are several steps needed to remove academic plans from RadGrad2.

* [x] Remove the AcademicPlanCollection. This includes updating the fixtures. There are 36 'import { AcademicPlans }' instances.
* [x] Remove FavoriteAcademicPlanCollection. There are 24 'import { FavoriteAcademicPlans }' instances.
* [x] Remove the Academic Plan Explorer.
* [x] Remove the Advisor's Academic Plan viewer and builder.
* [x] Remove the FavoriteAcademicPlans tab
* [x] Update HelpMessages and Landing Page Guided Tours to no longer mention Academic Plans
* [x] Update the fixtures to not include academic plans
* [ ] Update the migration script to remove academic plans from RadGrad1 download data.

**Comment by cammoore** [comment]
Do we want to remove them or just not validate if a student satisfies the plan? Without plans how does a student know what courses they need to take?

**Comment by cammoore** [comment]
* [ ] Admin UpdateUserForm.tsx doesn't allow the admin to update the user's favorite academic plans.

**Comment by philipmjohnson** [comment]
As discussed yesterday, we can implement an advisor-specified "default" set of "favorite" courses for all new RadGrad accounts. Then, the user can augment those to fill out their degree plan.

**Comment by cammoore** [comment]
Getting an error in the VerficationRequests.methods.test-app. Not sure what happened. Removing Academic Plans and Plan Choices shouldn't affect VerificationRequests.

**Comment by cammoore** [comment]
Had to restart from master again. Using issue-266-v2.

**Comment by cammoore** [comment]
Updated the fixtures. Am going to close this issue and open another for the images and slideshows.

**Comment by cammoore** [comment]
Forgot about PlanChoices. Going to remove them.
