### ISSUE TITLE
Remove "DesiredDegrees" from RadGrad2

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#279]
Please do work for this task in a branch called issue-279.

As "Degrees" from the Explorer is no longer needed, this issue is refactoring the codebase by deleting all code instances of "Degrees" and related functionality.

- [x] DesiredDegreesCollection
- [x] Components
- [x] Imports
- [x] Typings
- [x] EXPLORER_TYPE.DEGREES
- [x] Relation with AcademicPlans
- [ ] Update HelpMessages and Landing Page Guided Tours to no longer mention degrees

**Comment by cammoore** [comment]
* Updated the tests so they pass.
* Removed Degrees from explorer menus.
* Removed Degree pagination and scroll state from redux.
