### ISSUE TITLE
Create Redux state to manage the state of choices selected for OpportunitySortWidget and CourseFilterWidget

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#286]
Please do work for this task in a branch called issue-286.

Because the expected workflow of a user when viewing the Explorers is clicking on an item -> checking out that item -> going back to the explorers, it would be a good UX experience if we actually save their selected sort/filter choices for the Opportunity and Course explorers. Especially since with the RadGrad re-design, the Opportunities Card Explorer now uses pagination and the pagination state will also get saved and managed by Redux state. The Courses Card Explorer did not go through a re-design treatment like Opportunities, but we still do save the scroll position of the Card Explorer. Therefore, we want to make sure that when a user goes back to the Explorers, that they are back to the same exact list of items that they were previously viewing.

**Comment by cammoore** [comment]
Done.
