### ISSUE TITLE
Implement the Student Home Page

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#30]
Please do work for this task in a branch called issue-30.

- [x] Student Home Menu
- [x] Student of Interest Widgets (Opportunities & Courses)
- [x] Student Feed Widget
- [x] Student Teasers Widget
- [x] Fix UI

**Comment by gcalica** [comment]
Need to fix a minor UI bug
https://github.com/radgrad/radgrad2/blob/b5ee7fa6ac3bf55af2f858a229c998c337961b3e/app/imports/ui/components/student/StudentOfInterestAdd.tsx#L103
