### ISSUE TITLE
Polish UI of Card Explorers

### ISSUE THREAD

**Issue by gcalica** [radgrad/radgrad2#301]
Please do work for this task in a branch called issue-301.

Not counting the Card Explorers for Opportunities, there were some minor changes to the other Card Explorers (Users is no longer part of Card Explorers btw). 

Things to check in each page:
* Reactivity
* Card Explorer Menu
  - Overall UI 
  - Any text
* Cards Widget
  - Update the checkForNoItems messages as their instructions are no longer updated because of the redesign.

- [ ] Academic Plans
- [ ] Career Goals
- [ ] Courses
- [ ] Interests

**Comment by cammoore** [comment]
This issue is old. We are doing it in other issues.
