### ISSUE TITLE
Review and improve settings file structure

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#319]
Please do work for this task in a branch called issue-319.

While documenting the settings file structure at https://www.radgrad.org/docs/developers/reference/settings, I discovered a few potential issues:

  * server-only CAS credentials may not be necessary.
  * Level criteria might be  better as server-only
  * databaseRestoreFileName might be better as server-only
  * "RadGrad" subsection does not seem helpful (all settings are for RadGrad).  Maybe move this to top-level, make them server-only as appropriate.
  * Is appLogging still needed? 
  * Is fixUserInteractions still needed?

For this issue, investigate and improve settings file structure if possible.

**Comment by cammoore** [comment]
* Level criteria can't be server-only. We provide hints to the students that use these properties.

**Comment by cammoore** [comment]
* server-only CAS is based upon the docs for atoy4:accounts-cas

**Comment by cammoore** [comment]
Moved some of the settings around.
