### ISSUE TITLE
Provide student login for development and testing

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#326]
Please do work for this task in a branch called issue-326.

AFAIK, there is no way to login as a student without using CAS. Although we can login as an admin and then click on a student to display a page, this is not totally equivalent to logging in as a student (for one thing, the subscriptions are different). 

It would be useful if, for development and testing purposes, there was a way to "really" login as a student using Meteor accounts.  

This mechanism could be enabled only when "development" is true in the settings file.

**Comment by cammoore** [comment]
When in development mode, Meteor.settings.public.admin.development === true, The Users.define uses default credentials for all users.

You will have to do a meteor reset and a meteor npm run start to create all the users with default credentials.
In development mode, RadGradLoginButtons sends all roles to signin page. It doesn't matter which role you choose. Provide the email and default credentials and you will be logged in as that user.
