### ISSUE TITLE
Restructure code base.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#328]
Please do work for this task in a branch called issue-XXX.

* [x]  Restructure codebase so that the directory structure and files within them observe our new architectural guidelines.
* [ ] Find dead code and move it into the radgrad2/archive directory.
* [ ] Rename classes when necessary. For example, too many classes are called "Card" this and "Card" that.   It's like a virus or something. Moving forward, I suggest that the only classes that are called "Card" are those that actually return a single Semantic UI Card object. (I don't know offhand if we even have any standalone classes like that.)

**Comment by philipmjohnson** [comment]
Let's make this issue just the first one. I'll create additional issues for the other ones. Then we can farm them out.
