### ISSUE TITLE
Ensure that subscriptions and withTracker occur only at "Page" level. 

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#334]
Please do work for this task in a branch called issue-334.

Moving forward, only "Pages" subscribe to publications from the database. They then pass data to components. Components should be "pure" and not subscribe to publications or use withTracker.

- [x] Ensure for all admin pages.
- [x] Ensure for all student pages.
- [x] Ensure for all advisor pages.
- [x] Ensure for all faculty pages.

**Comment by cammoore** [comment]
This is related to #261. When we finish this one we can close #261.

**Comment by cammoore** [comment]
I'll take admin pages.

**Comment by philipmjohnson** [comment]
Rashmi will take student pages, Jesse will take advisor, and Philip will take faculty.

branches will be: issue-334-(role)

**Comment by cammoore** [comment]
No more withTrackers in components/admin

**Comment by cammoore** [comment]
Working on landing pages and components.

**Comment by cammoore** [comment]
Done with landing.

**Comment by philipmjohnson** [comment]
Done with faculty pages.  This took more brain power than I expected!

**Comment by cammoore** [comment]
Starting on shared.

**Comment by cammoore** [comment]
Done with shared.

**Comment by cammoore** [comment]
No more withTrackers in components.
