### ISSUE TITLE
Proposal: RadGradContainer component

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#342]
Please do work for this task in a branch called issue-342.

Because the built-in Semantic UI "Container" component does not behave well, we tend to use the following workaround using a stackable Grid component:

```
<Grid stackable>
    <Grid.Row>
      <Grid.Column width={1} />
      <Grid.Column width={14}><HelpPanelWidget /></Grid.Column>
      <Grid.Column width={1} />
    </Grid.Row>
</Grid>
```

This provides 1/16 padding on each side until the width passes a threshold and then it effectively becomes full width.

This seems like a reasonable approach, particularly if we can abstract it into a simple React Component so that we can replace the above code with the following (that expands into it):

```
<RadGradContainer>
  <HelpPanelWidget/>
</RadGradContainer>
```

This simple change means that we can also re-implement the RadGradContainer in future if we come up with other approaches.

**Comment by cammoore** [comment]
Can we change it to a Grid.Row?

```
  <div id="faculty-home-page">
    <FacultyPageMenuWidget />
    <Grid stackable>
      <Grid.Row>
        <Grid.Column width={1} />
        <Grid.Column width={14}><HelpPanelWidget /></Grid.Column>
        <Grid.Column width={1} />
      </Grid.Row>

      <Grid.Row>
        <Grid.Column width={1} />
        <Grid.Column width={14}>
          <FacultyPageAboutMeWidget />
        </Grid.Column>
        <Grid.Column width={1} />
      </Grid.Row>
    </Grid>
  </div>
```

Becomes:
```
<div id="faculty-home-page">
    <FacultyPageMenuWidget />
    <Grid stackable>
      <RadGradContainer>
        <HelpPanelWidget />
      </RadGradContainer>
      <RadGradContainer>
        <FacultyPageAboutMeWidget />
      </RadGradContainer>
    </Grid>
</div>
```

**Comment by philipmjohnson** [comment]
The goal is to hide the reference to "Grid" entirely. Let's not reveal how it's implemented.  So, instead of:
 
```
<div id="faculty-home-page">
    <FacultyPageMenuWidget />
    <Grid stackable>
      <RadGradContainer>
        <HelpPanelWidget />
      </RadGradContainer>
      <RadGradContainer>
        <FacultyPageAboutMeWidget />
      </RadGradContainer>
    </Grid>
</div>
```

It would be:

```
<div id="faculty-home-page">
    <FacultyPageMenuWidget />
      <RadGradContainer>
        <HelpPanelWidget />
      </RadGradContainer>
      <RadGradContainer>
        <FacultyPageAboutMeWidget />
      </RadGradContainer>
</div>
```

Which leads to a cool simplification: allow multiple React components inside  a container. If there are more than one, then they are each in their own row.  So, the above can be simplified to:

```
<div id="faculty-home-page">
    <FacultyPageMenuWidget />
     <RadGradContainer>
        <HelpPanelWidget />
        <FacultyPageAboutMeWidget />
     </RadGradContainer>
</div>
```

**Comment by philipmjohnson** [comment]
As part of another project, I need to lay out a bunch of cards.  I decided to do a side-by-side comparison of <Container> vs <Grid> with an empty column on either side. What I found, surprisingly, was that if you add "fluid" to the container, and add 10px of left/right padding, the layout of the Container appears better than the Grid!  Here are some screenshots.  

The  top tabbed area is laid out with a fluid container, and the bottom tabbed area is laid out with the Grid. As you can see, the fluid container lays out more Cards in a row than the Grid does at various widths.

## Very wide windows seem  better with a fluid container
<img width="1840" alt="Screen Shot 2020-11-23 at 11 27 53 AM" src="https://user-images.githubusercontent.com/290288/100017492-10bf4880-2d7f-11eb-9703-7aa01ef2c908.png">

## Even moderate widths are better at some places

<img width="1470" alt="Screen Shot 2020-11-23 at 11 29 13 AM" src="https://user-images.githubusercontent.com/290288/100017570-34828e80-2d7f-11eb-92c4-185a1b243db4.png">

## On mobile, the extra padding is apparent

<img width="612" alt="Screen Shot 2020-11-23 at 11 30 19 AM" src="https://user-images.githubusercontent.com/290288/100017654-554ae400-2d7f-11eb-90bf-299babafd3aa.png">

The net of it is that the "Grid column hack" might not be as good as a "Fluid Container hack"!
