### ISSUE TITLE
Review: StudentIcePage, StudentIceWidget, and StudentIceColumn

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#354]
## Review Branch

https://github.com/radgrad/radgrad2/tree/review-354

## Files to be reviewed

* [StudentIcePage.tsx](https://github.com/radgrad/radgrad2/blob/review-354/app/imports/ui/pages/student/StudentIcePage.tsx)
* [StudentIceWidget.tsx](https://github.com/radgrad/radgrad2/blob/review-354/app/imports/ui/components/student/ice/StudentIceWidget.tsx)
* [StudentIceColumn.tsx](https://github.com/radgrad/radgrad2/blob/review-354/app/imports/ui/components/student/ice/StudentIceColumn.tsx)

## Checklists

* [Architecture](https://www.radgrad.org/docs/developers/reviews/reference/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/reviews/reference/design-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/reviews/reference/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/reviews/reference/react-checklist)

## Specific requests for this review

None.

## Due date

Monday, Dec 14, 1:30pm

## Documentation

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by cammoore** [comment]
* [ ] Arch-02: The directories for the pages and components don't match. pages/student vs components/student/ice.

 * [ ] StudentIcePage.tsx#L26 TS-02, React-05:  Should we use object deconstruction for the props?
 * [ ] StudentIcePage.tsx#L36 JS-03: Should we use the spread operator here?
 * [ ] StudentIcePage.tsx#L29 Are we using Containers?
 * [ ] StudentIcePage.tsx#L50 Do we need to type this as IHelpMessage[]?

 * [ ] StudentIceWidget.tsx#L27 The type "innov" doesn't match L30 type="Innovation". We should probably use the same type. This happens for the two other types.
 * [ ] StudentIceWidget.tsx#L30 Should this be a type? Also in StudentIceColumn L73, 75, 75, 90, 92, 94 we are using strings.
 * [ ] StudentIceWidget.tsx#L29-L34 Pass in earnedICE and projectedICE.

 * [ ] StudentIceColumn.tsx#L15 Should be an exported type?
 * [ ] StudentIceColumn.tsx#L21 JS-04: Use object deconstruction. That way we don't need to keep pulling out type from props.
 * [ ] StudentIceColumn.tsx#L42-L68 Should these be in a utilities file?
 * [ ] StudentIceColumn.tsx#L42-L68 React-01,02: Is not small. Where should the functions go?
 * [ ] StudentIceColumn.tsx#L100-L112 Should these be utility functions? They might be used by other components. The parameters and return values should be typed.
 * [ ] StudentIceColumn.tsx#L118-L120 Why are we doing this. We are passed the earnedICE and projectedICE in the StudentIceWidget. Why not use the parameters in the column?

 * [ ] PageIceCircle.tsx#L22-23 shows a different value for earned ICE than the StudentIceColumn.
 * [ ] PageIceCircle.tsx Arch-01: Is PageIceCircle.tsx named correctly? StudentIceColumnCircle.tsx?

**Comment by philipmjohnson** [comment]
Review 354

https://github.com/radgrad/radgrad2/blob/review-354/app/imports/ui/pages/student/StudentIcePage.tsx

L32, 36: why are props sent as ...props to one widget and as an explicit property to another? What is the rule to determine when to do one and when to do the other?  REACT-05?

https://github.com/radgrad/radgrad2/blob/review-354/app/imports/ui/components/student/ice/StudentIceWidget.tsx

L18: React.CSSProperties? Never seen this before. 

L45: should type be c, i, or e (rather than "comp", etc)  for consistency?

https://github.com/radgrad/radgrad2/blob/review-354/app/imports/ui/components/student/ice/StudentIceColumn.tsx

L56: You can get rid of the :string type declaration since it can be inferred. 

General:

Not sure about the "I" prefix: typescript community doesn't like it:
https://www.reddit.com/r/typescript/comments/fng5ji/what_is_the_common_convention_for_interface_names/

**Comment by RashmiAR** [comment]
In StudentIceColumn.tsx we need to pass earnedICE and projectedICE L119 and L120 through props from StudentIcePage.tsx
should we explicitly send props?

**Comment by philipmjohnson** [comment]
ARCH-02: Difference between components and page directory structure is OK.

Containers: wait until Hanna to resolve.

Inside a withTracker, make sure all properties are explicitly typed. 

Inside a withTracker, use const to define a typed version of all props, then return them as the variable name (see StudentIcePage.tsx)

Need to combine MenuIceCircle.tsx and PageIceCircle.tsx into one file. Get rid of PageIceCircle.

Use React.CSSProperties to type objects

**Comment by philipmjohnson** [comment]
Review summary:

  * @Jesse-McDonald will attempt to fix all issues identified by TODO: by next Monday meeting. 
  * @philipmjohnson Will update review guidelines based upon this discussion. (Done).

**Comment by philipmjohnson** [comment]
Added Technical Debt comments.
