### ISSUE TITLE
Review: AdminAnalyticsNewsletterPage

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#355]
For this review, we're going to review the AdminAnalyticsNewsletterPage and widget.

## Review Branch

[review-355](https://github.com/radgrad/radgrad2/tree/review-355)

## Files to be reviewed

* [AdminAnalyticsNewsletterPage.tsx](https://github.com/radgrad/radgrad2/blob/review-355/app/imports/ui/pages/admin/AdminAnalyticsNewsletterPage.tsx)
* [AdminAnalyticsNewsletterWidget.tsx](https://github.com/radgrad/radgrad2/blob/review-355/app/imports/ui/components/admin/analytics/newsletter/AdminAnalyticsNewsletterWidget.tsx)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](https://www.radgrad.org/docs/developers/reviews/reference/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/reviews/reference/design-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/reviews/reference/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/reviews/reference/react-checklist)

## Specific requests for this review

This widget uses redux. So it might be a good opportunity to see how we are using redux in RadGrad2.

For more information, see [How to manage UI state with Redux in RadGrad](https://www.radgrad.org/docs/developers/design/howto/manage-ui-state-with-redux).

Does the widget make sense to you?

## Due date

3 pm, Thursday, December 17th.

## Documentation

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by Jesse-McDonald** [comment]
This widget makes very little sense to me.  I can tell generally what it is doing, it is composing emails to students and sending them.  I cant see anything specific that doesnt make sense and didnt notice problems, but I might just not know what I am looking for.

**Comment by cammoore** [comment]
* AdminAnalyticsNewsletterPage#L5 React-04 import AdminAnalticsNewsletterWidget doesn't match the export default AdminAnalyticsNewsletterWidgetContainer.

 * AdminAnalyticsNewsletterPage#L33 Duplicate withInstanceSubscriptions. App.tsx#L91 already wraps all admin pages in a withInstanceSubscriptions.

 * AdminAnalyticsNewsletterPage Do we have documentation on using this page?

 * AdminAnalyticsNewsletterWidget#L43-51 Is there a better way of typing the redux functions? The function actually returns an INewsletterAction according to redux/admin/analytics/actions.ts#L83.

 * AdminAnalyticsNewsletterWidget#L82 Why jsdoc comment?

 * AdminAnalyticsNewsletterWidget#L84-116 Is this the right way to do things? We're setting the state based upon a change to the form.

 * AdminAnalyticsNewsletterWidget#L89-91 There isn't a form input with the name onSubmitInputMessage.

 * AdminAnalyticsNewsletterWidget#L135,200,257 Using jquery to get the '.adminMessage' class name seems weird. There isn't a component directly in this widget. It must be in AdminAnalyticsNewsletterMessagePreviewWidget. Why use a class name and not an id?

 * AdminAnalyticsNewsletterWidget#L322-324 Should this button be disabled if the Meteor.settings MAIL_URL has changeme in it?

 * AdminAnalyticsNewsletterWidget#L334 Label is bad. Should be something like Generate and newsletters to all students.

**Comment by philipmjohnson** [comment]
AdminAnalyticsNewsletterPage:

L11: REACT-07: Use React.CSSProperties.

L3, 4, 5: When do we call a component a "widget"?

AdminAnalyticsNewsletterWidget:

L174, 230, 287: Successfully mispelled.

L173, 183, 229, 239, 286,296: DESIGN-01: Create a local function to reduce six repeated calls to Swal.fire.

L132, 136, 198, 201, 255, 258: JS-06: Avoid Lodash map, filter, ec.

L128,194,250: DESIGN-01: The "onClickSend*" methods seem very similar.

I would like a discussion/tutorial of Redux and why it is needed here. According to the docs, Redux is good for global state management and not local component management. I don't see any global state here.

**Comment by RashmiAR** [comment]
1. In AdminAnalyticsNewsletterPage, We usually use export default page, but here we are using withInstanceSubscriptions.
2. In AdminAnalyticsNewsletterWidget, I am not very sure of how mapStateToProps and mapDispatchToProps works.
3. I see there are some hardcoded strings. Do we add it in some constant resource file and read it from there.
4. Comments

**Comment by philipmjohnson** [comment]
REACT-04: change to say the import must match the filename. Need another standard that the filename should match the widget name.  (It's OK to export the containerized version of the widget). 

Need to understand interaction between withInstanceSubscriptions (for example) and withTracker.  Is it order-dependent?

REACT-XX:  all global subscriptions and instance subscriptions should be in router, not at page. 

JS/TS:  Make sure comments in JSDoc notation /** */ is meaningful for JSDoc

Consider attempting to remove the "widget" suffix whenever possible unless name conflicts. 

Create an issue to replace lodash with builtins.

**Comment by philipmjohnson** [comment]
Consider a new global issue to change functions to arrow functions.

**Comment by philipmjohnson** [comment]
Added a technical debt comment.
