### ISSUE TITLE
Review: AcademicTermCollection.test.ts

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#358]
For this review, we're going to review the unit tests for the AcademicTermCollection.

## Review Branch

[review-358](https://github.com/radgrad/radgrad2/tree/review-358)

## Files to be reviewed

[AcademicTermCollection.test.ts](https://github.com/radgrad/radgrad2/blob/review-358/app/imports/api/academic-term/AcademicTermCollection.test.ts)

## Checklists

* [Architecture](https://www.radgrad.org/docs/developers/reviews/reference/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/reviews/reference/design-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/reviews/reference/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/reviews/reference/react-checklist)

## Specific requests for this review

Think about the things we want to test.

## Due date

(Indicate when the review meeting is scheduled to occur.)

## Documentation

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by philipmjohnson** [comment]
Taking this off the project board for now. We have more pressing fish to fry.
