### ISSUE TITLE
Change functions to arrow functions 

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#359]
Please do work for this task in a branch called issue-359.

According to our [JS Conventions](https://www.radgrad.org/docs/developers/checklists/js-ts-checklist#js-05-use-arrow-functions-when-appropriate), we should prefer arrow functions over use of the function keyword.

For this issue, review the code base and change occurrences of function keyword to an arrow function.

**Comment by cammoore** [comment]
Please don't change any of the test code to use arrow functions. [Mocha arrow functions](https://mochajs.org/#arrow-functions) are discouraged.

**Comment by cammoore** [comment]
Converted as many as I could. There are still a few functions left.
