### ISSUE TITLE
Remove the "Widget" component suffix when possible

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#360]
Please do work for this task in a branch called issue-360.

Many React components are named with "Widget".  In most (all?) cases, adding "Widget" just increases the length of the name without adding value.  

Remove occurrences of "Widget" from components in the following directories. Check off the directory when done:

- [ ] ui/components/shared/explorer
- [ ] ui/components/admin/analytics
- [ ] ui/components/admin/datamodel
- [ ] ui/components/advisor
- [ ] ui/components/faculty
- [ ] ui/components/student
- [ ] ui/components/shared/academic-plan
- [ ] ui/components/shared/moderation

**Comment by cammoore** [comment]
```ui/components/shared/academic-plans``` is going to be deleted soon. So don't worry about it.

**Comment by philipmjohnson** [comment]
Added to React Checklist, so will be taken care of through review process.
