### ISSUE TITLE
Replace lodash calls to builtin calls

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#361]
Please do work for this task in a branch called issue-361.

In ES6, the following lodash functions are now available as built-ins:

* [x] map
* [x] filter
* [x] reduce
* [x] pick

Search for the use of lodash, and see if you can eliminate it.  

For reference, see [10 Lodash features you can replace with ES6](https://www.sitepoint.com/lodash-features-replace-es6/).

**Comment by cammoore** [comment]
Also
 * forEach

**Comment by cammoore** [comment]
Done
