### ISSUE TITLE
Reduce subscription load for students 

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#364]
Please do work for this task in a branch called issue-364.

According to this spreadsheet, over 30% of user documents are related to the Course and Opportunity "Scoreboards":

https://docs.google.com/spreadsheets/d/1JpeYckXvvSTQyeKGBAH6kRtq-wW0DFqdjJAF7TkW5jA/edit?usp=sharing

Is there a way to avoid caching all of these documents until actually needed?

**Comment by cammoore** [comment]
We can probably remove the 
```
      globalSubs.subscribe(CourseInstances.publicationNames.scoreboard),
      globalSubs.subscribe(OpportunityInstances.publicationNames.scoreboard),
```
From the withGlobalSubscriptions. Then on ScoreboardPage subscribe to the two publications. This way the user won't see these documents until they visit the ScoreboardPage.
The scoreboard collections are purely client-side collections.

**Comment by cammoore** [comment]
Moved the CourseInstance and OpportunityInstance scoreboard subscriptions to the ScoreboardPage.
