### ISSUE TITLE
Remove subscriptions from landing page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#366]
Please do work for this task in a branch called issue-366.

When going to the landing page in Incognito mode (so not logged in), there are many unnecessary (and certain inappropriate) subscriptions:

<img width="1258" alt="Screen Shot 2021-01-11 at 9 27 28 AM" src="https://user-images.githubusercontent.com/290288/104228931-a0808b00-53ef-11eb-8841-1082a014c79d.png">

The only subscription that is actually necessary for this page is PublicStatsCollection. 

There are two consequences of the current situation:
  * Page display time takes a few seconds because over 4000 documents are requested from the server. Only 22 documents are actually required.
  * Populating the users and StudentProfileCollections make public some protected information.

Please remove unnecessary subscriptions from LandingPage.

**Comment by cammoore** [comment]
I moved the withGlobalSubscription from the App and put them in the protected routes. This greatly reduces the documents for the landing pages.

But we now have a race condition with the integration tests. The first test fails with an Undefined user profile. Apparently, the subscriptions aren't done before we try to do something. Not 100% sure where the error is occurring.

Have tried several changes, but nothing has worked so far.

**Comment by cammoore** [comment]
Turns out we need to wrap Users.getProfile in a try..catch block in the StudentProtectedRoute and the LandingHomePage. The subscriptions aren't initially finished loading so Users.getProfile throws an exception. Wrapping it in a try..catch block allows the processing to continue and we get the right page rendered eventually.
