### ISSUE TITLE
Fix "Failed to decode downloaded font" warning

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#367]
Please do work for this task in a branch called issue-367.

After logging in as the opq user, the following warning  appears in the console:

<img width="606" alt="Screen Shot 2021-01-15 at 8 35 47 AM" src="https://user-images.githubusercontent.com/290288/104765247-b0101480-570c-11eb-8f13-9f8f67975834.png">

Stackoverflow provides a large number of suggestions for fixing this. Probably one of them is right for our situation:

https://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font

**Comment by cammoore** [comment]
This is a part of the slick-carousel. We might be able to get rid of this package when we remove the guided tours.

**Comment by philipmjohnson** [comment]
Yes, let's remove react-slick and all associated RadGrad uses to fix this. It's the simplest path.

**Comment by philipmjohnson** [comment]
Solution:
* Remove react-slick, react-carousel, and all code (i.e. guided tours) that depends on it.
* Move it to the archive/ directory.
