### ISSUE TITLE
Images from Cloudinary being requested using http, not https

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#368]
Please do work for this task in a branch called issue-368.

When logging in as the student opq@hawaii.edu, the following warning appears in the console:

```
Mixed Content: The page at 'https://radgrad2.ics.hawaii.edu/#/student/opq@hawaii.edu/home' 
was loaded over HTTPS, but requested an insecure element 
'http://res.cloudinary.com/radgrad/image/upload/v1609887715/fklw5mdthdi57f6km0lz.jpg'.
```

The reason this occurs is because when a database is dumped, the image URLs for users are dumped using the http: protocol (http://res.cloudinary.com/radgrad/image/upload/v1609887715/fklw5mdthdi57f6km0lz.jpg). 

One approach would be to store the URL using a "protocol relative URL", such as "//res.cloudinary.com/radgrad/image/upload/v1609887715/fklw5mdthdi57f6km0lz.jpg". 

However, this is apparently an anti-pattern: https://webhint.io/docs/user-guide/hints/hint-no-protocol-relative-urls/

So, maybe we should instead force https as the protocol for all cloudinary images?

**Comment by cammoore** [comment]
We're using the URL provided by the cloudinary upload tool. We can change the code to replace http with https. We're going to need a one-time button to go through all the profiles updating their picture url to https if it is a cloudinary url.

**Comment by philipmjohnson** [comment]
Need to update the converter for RadGrad1 to RadGrad2 data to ensure that cloudinary urls are HTTPS.

**Comment by philipmjohnson** [comment]
I just loaded the file produced by the new converter and the image links are broken:

<img width="961" alt="Screen Shot 2021-02-15 at 9 13 44 AM" src="https://user-images.githubusercontent.com/290288/107985519-5189c080-6f6e-11eb-8ff2-1f7a18ff7c80.png">

Note the extra slash ("...//radgrad..."))

@RashmiAR Did you test the output produced by your changes to the converter code to make sure it works correctly?
