### ISSUE TITLE
Create Terms and Conditions checklist item

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#376]
Please do work for this task in a branch called issue-376.

We should develop a terms and conditions document for users because the current design of the users and studentprofile collections means that all students can determine the name and email associated with all other users in the system. To comply with FERPA, we should make RadGrad use contingent upon students agreeing to reveal their name and email address to other students in the system. 

One approach is a pop-up dialog on first login to the system where students can read a terms and conditions document and click agree to proceed.  If they agree, then the time and date of the agreement is logged in their profile. If they don't agree, then they are logged out of the system.

**Comment by cammoore** [comment]
Do we want to remove the student's data if they don't agree?

**Comment by cammoore** [comment]
Updating this issue to make the Terms and Conditions to be a high priority checklist item. This should be the first item shown to the student. If they agree we can move it to the done checklist items.

Periodically, we can move this checklist item to the needs review group.

Moving this to the Todo column.

**Comment by philipmjohnson** [comment]
Closing this issue. It will be re-specified as part of the checklist implementation.
