### ISSUE TITLE
Computer Engineering Instance Design and Implementation

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#377]
Here are the steps for the implementation of a Computer Engineering (CE) instance of RadGrad:

- [x] Create an initial set of Interests, Career Goals, and Opportunities.
- [x] Create an initial set of descriptions for each Interest, Career Goal, and Opportunity. Include Teasers whenever possible.
- [x] Create a "fixture" for the CE instance. This is a snapshot json file with Interests, Career Goals, Opportunities, Teasers, and Courses. 
- [x] Create a pilot deployment for the CE instance using a Digital Ocean droplet. 
- [ ] Design a pilot study protocol.
- [ ] Perform a pilot study of the pilot deployment with a handful of CE community members including a few students and Galen Sasaki.
- [ ] Write up results of pilot study and recommendations for improvements to instance.

**Comment by cammoore** [comment]
We need to figure out how to add the concept of Concentrations to RadGrad.

 * Is it a new Collection?
 * Is it a special kind of interest?
 * How do we limit students from picking more than one? Update the StudentProfile? Have a StudentConcentrationCollection?
 * How can we make this more generic for other degree programs or universities?

**Comment by jatinp101** [comment]
Just moved tables to new files and updated them with their descriptions and respective teasers. Many of them will be reused from RadGrad CS so I've gone through and labeled it as such.

**Comment by jatinp101** [comment]
Update on Concentrations the best way would be just to treat it as an Interest. I've gone through and wrote it in the documentation/

**Comment by philipmjohnson** [comment]
Closing this issue.  I think the pilot study needs to wait until the pages are implemented better.
