### ISSUE TITLE
Implement new menubar

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#379]
Please do work for this task in a branch called issue-379.

Please redesign the RadGrad student menu. The goal is to maximize the visibility of pages and minimize searching by providing access to all "top-level" pages on the menubar. This means that the menubar may wrap to multiple rows depending upon the width of the screen, which is OK.  

Here are the menubar items:

* Checklists: Goes to a new page displaying checklist items. Could have a notification number displayed listing the number of checklist items in the Improve state.
* Interests: Goes to the Interests Explorer
* Careers: Goes to the Career Explorer.
* Courses: Goes to the Courses Explorer
* Opportunities: Goes to the Opportunities Explorer
* Planner: Goes to the Degree Planner
* Verification: Goes to a new page where any opportunities requiring verification will be shown. Could include a notification number when there are opportunities to verify.
* Privacy: Goes to a new page where the user can specify the visibility of their info
* ICE: Goes to page documenting their current ICE status
* Levels: Goes to a page documenting their current Level and explaining what they need to do next.
* Reviews: Goes to a new page where they can fill out reviews for completed courses and opportunities. Could include a notification number when there are any courses/opportunities to review.
* News: Goes to a new page when news stuff.

When the menu item goes to a new page, please create an empty page that this menu item navigates to.

The goal is to have a "skeleton" of the new design available so that Rashmi and Hanna can easily get into implementation work.

**Comment by cammoore** [comment]
The skeleton is up, but I'm not going to merge it into master. I'm just going to close this issue. If you want to run the skeleton switch to issue-379.

I'll try to keep merging master into issue-379.

**Comment by cammoore** [comment]
Merged into master
