### ISSUE TITLE
Implement new Landing page design

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#380]
Please do work for this task in a branch called issue-380.

Here is the design:

<img width="319" alt="Screen Shot 2021-02-05 at 8 42 30 AM" src="https://user-images.githubusercontent.com/290288/107075496-4674aa80-678e-11eb-9a9c-2e87f61b3c6c.png">

Implementation notes:
* Leave room for "Factoids" in first panel, to be added at a later time.
* The "tagline" should be set in the settings file.
* The instance name (in the above case, "UHM/ICS") should also be set in the properties file.
* Note that all text may evolve from the mockup. We can't cut and paste PNG images containing text, for example.
* Please be sure to move all old Landing code to the archive/ directory.

**Comment by cammoore** [comment]
Done. We might want to change some of the padding to make the page have less whitespace.
