### ISSUE TITLE
Implement Landing Page "Factoids"

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#385]
Please do work for this task in a branch called issue-385.

The Landing Page includes a rotating set of Factoids.  The goal of the Factoids is to provide visitors to the public landing page with a sense for the contents of a RadGrad instance without revealing any personally identifying information. 

See the [Factoid Content Specification Document](https://docs.google.com/document/d/1EjrzZYaAnRnPY9ZC3mcprv5m-DC3Zo1tk3hXzwvhJN4/edit?usp=sharing) for details. 

I suggest that the implementation proceed in two phase:

  1. Implement the Factoid Component with a fixed set of Factoids that are hard-wired into the PublicStats collection.
  2. After review and acceptance of the UI, implement the cron job to dynamically update the set of Factoids each day. 

The implementation will probably consist of a "base class" called "Factoid" that has at least two methods:

  * render():  used to return a JSX component that displays a Factoid in the landing page
  * update(): a method that runs on the server-side once a day to update the PublicStats collection with the data necessary to render a Factoid.

The PublicStats collection's singleton document could have a single field called "FactoidData" which is an object whose fields are Factoid names with values being an object containing fields with the data for that Factoid.  For example:

```
{
  :
  FactoidData: {
    InterestsFactoid: { 
      name: "C++", 
      numStudents: 24, 
      numOpportunities: 12, 
      numCourses: 2,
      description: "The C+ language is most commonly used for systems programming..."
      },
      :
}
```

**Comment by cammoore** [comment]
The problem with the PublicStatsCollection is it has many documents that have the schema { key: string, value: string }. Factoids don't follow this schema.

I think we might need a FactoidCollection with a singleton document. RadGrad will update the document with a SyncedCron. The landing page can then subscribe to the FactoidCollection and get a single document.

**Comment by cammoore** [comment]
Added new FactoidCollection and UI. 
At startup, we update the factoids and start a cron job to update the factoids every 24 hours. The career goal, interest, opportunity, and review factoids are randomly selected from the respective collections.
