### ISSUE TITLE
Implement Checklist Processing infrastructure

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#386]
Please do work for this task in a branch called issue-386.

The [Checklist Item Content Specification](https://docs.google.com/document/d/1mx4Eh4vWjaEohW3cp6Fq7EhHjD9p6TkOIfl2981ncU8/edit?usp=sharing) provides a guide to the desired behavior of the Student Home Page, as well as a preliminary design sketch at the bottom of the document. 

To implement this behavior, we need to first create a general mechanism for defining and executing checklist items. Second, we can implement the behavior for specific checklist items in an incremental fashion. During the second phase we can add additional representations such as Timestamps as needed.

While the above specification document focuses on checklist items for students, we will probably want to implement checklist items for other roles, such as Faculty or Advisors. Fortunately, once we have infrastructure for students, we can easily extend it to other roles.

**Comment by cammoore** [comment]
Have an initial implementation. There are some parts that aren't done.

* New reviews for future courses or opportunities.
* Signing out the student if they don't accept the terms and conditions.
* Sending an email to the admin to remove the student who doesn't agree with the terms.
I'm going to keep this issue open, and also merge it into master.

**Comment by philipmjohnson** [comment]
Great start!!!!!!

I notice that opq on master needs three issues even though they have a bunch through their career goals:

<img width="998" alt="Screen Shot 2021-02-20 at 2 04 47 PM" src="https://user-images.githubusercontent.com/290288/108611760-d2d5be80-7385-11eb-965c-3a4832dcb2cd.png">

This, of course, is confusing. One solution is to say that as as long as they have three interests through some mechanism it's OK?

**Comment by cammoore** [comment]
We could not show the interests associated with career goals.

**Comment by philipmjohnson** [comment]
Hmm. This is an interesting UX issue. This person has plenty of interests already specified---it seems artificial to say "You need to make three more that aren't associated with career goals..." We don't want them adding stuff at random just to satisfy the checklist item.

I also think it's not good to "hide" Career Goal interests; that makes the system harder to understand. Instead, maybe it's better to make it more explicit that some Interests are implicitly defined as a result of specifying a Career Goal. In the Interest Checklist, could you have a set of rows like:

```
Interests implicitly defined by a Career Goal:
  * Hardware, HCI, Networks (AI Engineer)
  * Software Engineering, C++, Javascript (Full Stack Engineer)

Interests manually added:
  * None so far
```

Or something like that?

**Comment by cammoore** [comment]
Now sign out the students who don't approve of the terms.

Going to close this issue. We can create new issues for the checklists.
