### ISSUE TITLE
Remove student icons and number of students from explorer item descriptions

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#387]
Please do work for this task in a branch called issue-387.

The Interests Explorer loads slowly because, for each Interest, it must retrieve student icons from Cloudinary and compute the number of students associated with that interest via a Meteor method call. 

For the overview page that lists all of the interests, this additional information on students is not important. Students can click the "View more" button to get details, including students, reviews, and so forth. 

Modify all Explorers (not just Interest) to not display this student-level information. This should fix performance issues for the Interest Explorer.

**Comment by cammoore** [comment]
Removed the Students Participating.
