### ISSUE TITLE
Redesign: Landing Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#388]
Please do work for this task in a branch called issue-388.

The current implementation of the Landing Page leaves a few things to be desired. For example:

At 1000px, the middle section stacks to single column. That doesn't seem right.

The fonts vary from quite small (middle of page) to quite large (bottom of page). Seems like font size should be more consistent.

If you pull down the login menu at the bottom and select ...as student (for example), it goes to page with "undefined LOGIN" at top:

<img width="938" alt="Screen Shot 2021-02-08 at 1 21 31 PM" src="https://user-images.githubusercontent.com/290288/107293959-a11d3900-6a10-11eb-9fbd-64711d57433e.png">

**Comment by philipmjohnson** [comment]
Just checked out the revised landing page and it seems the graphics are not aligned:

<img width="240" alt="Screen Shot 2021-02-13 at 9 09 01 AM" src="https://user-images.githubusercontent.com/290288/107859061-3cc8f380-6ddb-11eb-821e-765938772e2f.png">

Can the white disk be placed exactly within the green circle?

**Comment by philipmjohnson** [comment]
Also, the links to the Landing Page explorers are still "easter eggs".  They are simply bold text, not clearly identifiable as links. 

Please consider a design in which there are buttons to these explorers to make them visually clear. Perhaps a separate pane in the landing page?

**Comment by hannaparkUH** [comment]
![image](https://user-images.githubusercontent.com/53065327/108049236-1928c780-6fec-11eb-8a2a-6369cccf571e.png)
How about adding "COURSES" instead of "STUDENTS, FACULTY, ALUMNI"?

**Comment by hannaparkUH** [comment]
> Just checked out the revised landing page and it seems the graphics are not aligned:
> 
> <img alt="Screen Shot 2021-02-13 at 9 09 01 AM" width="240" src="https://user-images.githubusercontent.com/290288/107859061-3cc8f380-6ddb-11eb-821e-765938772e2f.png">
> 
> Can the white disk be placed exactly within the green circle?

Sure. But I think the offset white background look better.

**Comment by philipmjohnson** [comment]
RE: Adding Courses: I think adding courses is essential (because how else will they get to the course explorer). But the number of users is kind of an important measure (we have 700+ currently). So I don't think that should be removed from the system. I also don't think those buttons are clearly a link yet---they look like a label.

RE: white disc/circle.  To me, it doesn't look intentional.  It looks like we don't know html/css good enough to line things up correctly.

**Comment by hannaparkUH** [comment]
![image](https://user-images.githubusercontent.com/53065327/108282052-07970b00-7125-11eb-8855-feee38334b96.png)
![image](https://user-images.githubusercontent.com/53065327/108282096-18e01780-7125-11eb-9312-aa5670b6deb8.png)
I think that the menu links look more clear. Let me know what you think. 

The icons are modified.

**Comment by philipmjohnson** [comment]
OK, I agree that the menu is better than links underneath the numbers. 

Please go ahead and implement this.  Thanks!
