### ISSUE TITLE
Manually test data model menu

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#394]
Having just gone through the UI for the "Data Model" menu in RadGrad2, I am not convinced that this code is fully functional.

For this task, manually verify that all of the collections in the Data Model menu can be manipulated correctly using the UI. This means that you can successfully add a new document, update all of the fields for an existing document, and (if available) delete a document. 

To do this, just bring up an instance in development mode using the default fixture, and go through each menu. 

Report the results as a comment to this issue.

**Comment by cammoore** [comment]
We have to be careful about this. Some collections are highly linked and making changes may be very bad. 

Some fields can't be changed w/o updating other collections. Slugs is an example of this. Another example is CourseInstance, does it make any sense to be able to change the student?

**Comment by philipmjohnson** [comment]
@cammoore Yes, I totally agree. Since each collection has its own page in the data model, we can use the Page Header to document any issues the administrator should be aware of when managing the entity. 

If you want to take a first pass through the pages and update the documentation with anything you can think of, that would be a good first step!

**Comment by jatinp101** [comment]
Which page is the data model menu on for radgrad2?

**Comment by philipmjohnson** [comment]
@jatinp101 Login as the admin, then it's the pull down menu  called "Data Model".

**Comment by jatinp101** [comment]
![image](https://user-images.githubusercontent.com/42600077/108579067-5d0c1d00-72c9-11eb-93ef-292298b0bbfe.png)
Had an issue with updating Sample Student 2021 in Academic Year instances

But besides that, it looks fine and @cammoore has a good point about how all the collections are highly linked. I was also unsure what it meant to create a verification request as students are the ones who create it (from my understanding) maybe it might not be necessary to have that?

**Comment by philipmjohnson** [comment]
The Add User form is broken.

**Comment by cammoore** [comment]
* [ ] Academic Terms
* [ ] Academic Year Instances
* [ ] Career Goals
* [ ] Course Instances
* [ ] Courses
* [ ] Feeds
* [ ] Interests
* [ ] Interest Types
* [ ] Opportunities
* [ ] Opportynity Instances
* [ ] Opportunity Types
* [ ] Reviews
* [ ] Slugs
* [ ] Teasers
* [ ] Users Admin
* [ ] Users Advisors
* [ ] Users Faculty
* [ ] Users Student
* [ ] Verification Requests

**Comment by cammoore** [comment]
AcademicYearInstances had the wrong update schema. Can only update the year and retired.

**Comment by cammoore** [comment]
Feeds 'work', but need to be redesigned. I don't think you should be able to update the feed's users.
