### ISSUE TITLE
Courses Explorer takes too long to load

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#396]
Please do work for this task in a branch called issue-396.

On radgrad2.ics.hawaii.edu, when logged in as Ophelia, the courses explorer takes around five seconds to load, which is too long. 

I think it's highly likely that the culprit is the display of the forecast for this course for the next nine semesters:

<img width="1204" alt="Screen Shot 2021-02-15 at 12 19 42 PM" src="https://user-images.githubusercontent.com/290288/107998045-58bdc800-6f88-11eb-99cc-f2773d40e6be.png">

Displaying this information in the Explorer overview page is unnecessary; students won't need this information at this point. 

So, see if removing this information from this page resolves the slow loading time.  Even if it doesn't, it's appropriate to remove it.

**Comment by hannaparkUH** [comment]
Here is the mockup for the courses page.
https://www.figma.com/file/iJwSoxnGq39WBOGj3YJgvW/RadGrad2---courses?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Will be addressed as part of #414.
