### ISSUE TITLE
Redesign: Student Interests Explorer Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#397]
Please do work for this task in a branch called issue-397.

## Current design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 24 59 PM" src="https://user-images.githubusercontent.com/290288/108004527-3634aa80-6f9a-11eb-9e53-9113954f08d6.png">

## UI Issues

* Two columns creates a whitespace "gutter" along left side after scrolling.
* Does not indicate the interests implied by selecting a career goal.

## UX Issues

This page needs to answer the following questions:

  * What are interests?
  * Why do I want to add an interest to my profile?
  * What are the two ways that interests can be associated with my profile?
  * How do I add an Interest to my profile?
  * How do I remove an Interest from my profile?

**Comment by hannaparkUH** [comment]
The mockup is posted on Figma. Should I upload the image here?

**Comment by philipmjohnson** [comment]
Perhaps make a separate Figma project/page for each issue, and then post the link here? That makes it easy to use the issue comments to get to the corresponding Figma image, which is easiest to make comments on.

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/n96EJt61wuPnR14YxkFS4m/RadGrad2-interests?node-id=0%3A1
