### ISSUE TITLE
Implement: Student Career Goals Explorer Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#398]
Please do work for this task in a branch called issue-398.

## Current design

<img width="1181" alt="Screen Shot 2021-02-17 at 9 05 46 AM" src="https://user-images.githubusercontent.com/290288/108254673-69dd1500-70ff-11eb-9981-08fbe19c1af8.png">

## UI Issues
* Two columns creates a whitespace "gutter" along left side after scrolling.
* Does not indicate the interests implied by selecting a career goal.

## UX Issues

This page needs to answer the following questions:

  * What are career goals?
  * Why do I want to add an career goal to my profile?
  * How do Career Goals relate to Interests?
  * How do I add a Career Goal to my profile?
  * How do I remove a Career Goal from my profile?

**Comment by hannaparkUH** [comment]
Here is the mockup for the career goals page.
https://www.figma.com/file/EiXfWsnWt3tmgFIccjokyO/RadGrad2---career-goals?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="1005" alt="Screen Shot 2021-03-10 at 1 34 57 PM" src="https://user-images.githubusercontent.com/290288/110713138-7a842680-81a5-11eb-85ec-a9c058462b4d.png">
