### ISSUE TITLE
Implement: Student Opportunities Explorer Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#399]
Please do work for this task in a branch called issue-399.

## Current Design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 32 31 PM" src="https://user-images.githubusercontent.com/290288/108004748-c672ef80-6f9a-11eb-85e1-c47a673e9cfc.png">

## UI Issues

* Take out the Internships section (we will need a separate page for this once InternAloha is available).
* Should this page have a consistent look and feel with Courses, Career Goals, and Interests?
* Don't display icons on this page---could make page load too slow.

## UX Issues

This page needs to answer the following questions

* What are Opportunities, and why are they important?
* Why should I add an Opportunity to my profile? 
* How do Opportunities relate to ICE?

**Comment by hannaparkUH** [comment]
Here is the mockup for the opportunities page.
https://www.figma.com/file/v6VZ6rHZuXxOiaqL1YmZs3/RadGrad2---opportunities?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Mockup:

<img width="709" alt="Screen Shot 2021-03-13 at 10 15 54 AM" src="https://user-images.githubusercontent.com/290288/111043173-34b5a100-83e5-11eb-8e61-0b1d211114f7.png">
