### ISSUE TITLE
Redesign: Student Degree Planner Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#400]
Please do work for this task in a branch called issue-400.

## Current Design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 36 26 PM" src="https://user-images.githubusercontent.com/290288/108004900-48631880-6f9b-11eb-8673-9a0c01e4927e.png">

## UX Proposal (for discussion)

The Degree Planner is one of the most important, and most complicated parts of RadGrad.  Here are some ideas for how we could simplify Degree Planning by automatically adding Courses and Opportunities:

1. Allow the RadGrad administrator to define a set of "required courses".  Then, when a new user is registered with the system, these courses are automatically added to their profile. 

2. When a user adds an interest or career goal to their profile, one or more "matching" courses and opportunities can be implicitly added to their profile. 

3. When a user removes an interest or career goal, no change is made to their profile.

4. When a user completes a course, this course (if present in their profile) is automatically removed from their profile. 

5. In the Degree Planner page, there is an easy way for a user to pop up a modal window that contains the same information as in the corresponding Explorer drilldown page.  The advantage of a modal is that the user is returned to the Degree Planner page immediately when they dismiss the modal.  Since courses and opportunities are going to be added to the user profile by the system, the user needs an easy way to find out more about the course to see if they are actually interested in it. 

6. Users can always manually add and manually delete courses and opportunities from their profile to "override" these implicit suggestions.

From prior experience, we know that having all 80+ courses and/or opportunities in the Degree Planner is too many. What we don't know is what is the upper limit of "not too many".  For example, I feel that 12 courses and 12 opportunities are definitely "not too many".  But what about 20? What about 30? We need to think about this upper limit if we are going to implement an approach where courses and opportunities are automatically added, because we might need to cap/disable if this limit is reached. 

What is exciting about this approach is that it can simplify the UX: Add some interests and career goals, and then go directly to the Degree Planner!  It also provides a concrete meaning for RadGrad "recommendations": a recommendation is a course or opportunity that RadGrad automatically adds to your profile.

**Comment by hannaparkUH** [comment]
Here is the mockup for the degree planner page.
https://www.figma.com/file/G2cStiD0iBBNl9RuWxXISd/RadGrad2---degree-planner?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="615" alt="Screen Shot 2021-03-09 at 9 56 21 AM" src="https://user-images.githubusercontent.com/290288/110529846-d2476280-80bd-11eb-9fcb-b5f38936a8d5.png">

**Comment by cammoore** [comment]
I've switched the layout row-based and now we can display all the academic years.
Shrank the padding so the terms are smaller.
Fixed the subscriptions so the future enrollment is correctly displayed.
Going to close this issue. If we want other improvements we can open another issue.
