### ISSUE TITLE
Implement: Student Verification Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#401]
Please do work for this task in a branch called issue-401.

## Current (non) Design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 38 03 PM" src="https://user-images.githubusercontent.com/290288/108004969-7c3e3e00-6f9b-11eb-9a6e-8d32015391a7.png">

## UX Issues

This page should answer the following questions:

1.  What is a verification? Why are they needed? How do I do it?
2. What Opportunities are currently available for me to verify?
3. What verifications have been denied, and how can I resubmit?

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="559" alt="Screen Shot 2021-03-13 at 10 17 31 AM" src="https://user-images.githubusercontent.com/290288/111043199-6169b880-83e5-11eb-9991-0fbe11dc612b.png">

**Comment by cammoore** [comment]
Removing verification from the degree planner.

**Comment by cammoore** [comment]
Added required documentation for defining VerificationRequests.
