### ISSUE TITLE
Implement: Student Privacy Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#402]
Please do work for this task in a branch called issue-402.

## Current (non) Design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 39 00 PM" src="https://user-images.githubusercontent.com/290288/108005022-a0018400-6f9b-11eb-8c02-0160f330323d.png">

## UX Issues

This page should answer the following questions:

1. What can I reveal to others in this community?
2. What are the pros and cons of revealing this information.
3. How can I see what is revealed about me to others?

**Comment by hannaparkUH** [comment]
Here is the mockup for the privacy page. 
https://www.figma.com/file/khpDIpNxZ8BaLdvDMIDEhp/RadGrad2---privacy?node-id=0%3A1

**Comment by hannaparkUH** [comment]
I am not sure that the "academic plan" needs to be included.

**Comment by philipmjohnson** [comment]
## New Design

Figma: https://www.figma.com/file/khpDIpNxZ8BaLdvDMIDEhp/RadGrad2---privacy?node-id=0%3A1

### Profile Icon

<img width="979" alt="Screen Shot 2021-03-05 at 10 23 50 AM" src="https://user-images.githubusercontent.com/290288/110169700-2809cb00-7d9d-11eb-87dd-d949206fb843.png">

### Profile Label
<img width="459" alt="Screen Shot 2021-03-05 at 10 24 05 AM" src="https://user-images.githubusercontent.com/290288/110169724-30fa9c80-7d9d-11eb-82b7-1903a66829f3.png">

### Initial Privacy Page for new user

<img width="1038" alt="Screen Shot 2021-03-05 at 10 24 23 AM" src="https://user-images.githubusercontent.com/290288/110169754-3bb53180-7d9d-11eb-8a4e-a488b4496e87.png">

### Example Privacy page with settings
<img width="1034" alt="Screen Shot 2021-03-05 at 10 24 15 AM" src="https://user-images.githubusercontent.com/290288/110169788-4a034d80-7d9d-11eb-878e-cb00fafd6fba.png">
