### ISSUE TITLE
Implement: Student ICE Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#403]
Please do work for this task in a branch called issue-403.

## Current Design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 41 04 PM" src="https://user-images.githubusercontent.com/290288/108005107-dccd7b00-6f9b-11eb-9db0-fc1d293d3eb4.png">

## UI Issues

* Text at bottom of page needs rethinking.

## UX Issues

* This is an informational page about ICE.  How can we best communicate this idea to students?
* Should we embed a video on this page with more explanation?

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/YALPtjdFfhZSsqxAFj3YIq/RadGrad2---ICE

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="798" alt="Screen Shot 2021-03-17 at 3 39 42 PM" src="https://user-images.githubusercontent.com/290288/111560719-3231af00-8737-11eb-8806-0ae3bd84ddec.png">
<img width="811" alt="Screen Shot 2021-03-17 at 3 39 56 PM" src="https://user-images.githubusercontent.com/290288/111560729-39f15380-8737-11eb-94c6-0217edbe0d82.png">


<img width="822" alt="Screen Shot 2021-03-17 at 3 40 07 PM" src="https://user-images.githubusercontent.com/290288/111560735-3f4e9e00-8737-11eb-855a-2cb0c7733e2c.png">
