### ISSUE TITLE
Implement: Student Levels Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#404]
Please do work for this task in a branch called issue-404.

## Current Design

<img width="1340" alt="Screen Shot 2021-02-15 at 2 41 49 PM" src="https://user-images.githubusercontent.com/290288/108005159-07b7cf00-6f9c-11eb-9438-f47d624adbe5.png">

## UI Issues

* The top part of this page looks junky.  A huge box with only one person in it? 
* The six level box explanations are just thrown in there without any context.

## UX Issues

* We want to help users understand what Levels are.
* Perhaps an embedded short video would be useful?

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/rWIwN6GRhhqWZ0w4ePybtr/RadGrad2---level

**Comment by philipmjohnson** [comment]
<img width="614" alt="Screen Shot 2021-03-25 at 11 04 51 AM" src="https://user-images.githubusercontent.com/290288/112543507-f495dd00-8d59-11eb-8dc1-db2d83133eed.png">
