### ISSUE TITLE
Implement: Student Community Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#406]
Please do work for this task in a branch called issue-406.

## Current (non) Design

<img width="1174" alt="Screen Shot 2021-02-15 at 2 44 03 PM" src="https://user-images.githubusercontent.com/290288/108005268-52d1e200-6f9c-11eb-876e-407a362737de.png">

## UX Issues

* What should go in this page? Possible answers include:
  * Recently added/updated interests, opportunities, career goals, courses.
  * Students who achieved a new Level
  * Profiles of students, perhaps organized by matching interests? 
  * Upcoming Opportunities (i.e. based on their event date)

**Comment by philipmjohnson** [comment]
https://www.figma.com/file/0H3hRIjjgvBETqfXPshzhn/RadGrad2---community?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Awaiting redesign:
   * Need a feed component to see what's changed in the site recently.
   * Get rid of opportunity listing, it doesn't make sense here.

**Comment by hannaparkUH** [comment]
Updated. https://www.figma.com/file/0H3hRIjjgvBETqfXPshzhn/RadGrad2---community

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="676" alt="Screen Shot 2021-04-08 at 7 53 33 AM" src="https://user-images.githubusercontent.com/290288/114074005-a0055e00-983f-11eb-8246-d1c932e50931.png">

**Comment by philipmjohnson** [comment]
Initial implementation is complete. Still need to add Feeds and Events:

<img width="1311" alt="Screen Shot 2021-04-13 at 10 03 37 AM" src="https://user-images.githubusercontent.com/290288/114613902-99138c80-9c3f-11eb-9ece-af1299604440.png">

**Comment by philipmjohnson** [comment]
Still need to implement:

* Upcoming Events
* Community Activity
* Top RadGrad Students

**Comment by philipmjohnson** [comment]
Upcoming events as separate issue now.
