### ISSUE TITLE
Implement: Student Career Goal Drilldown Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#410]
Please do work for this task in a branch called issue-410.

## Current design

<img width="1357" alt="Screen Shot 2021-02-16 at 3 24 02 PM" src="https://user-images.githubusercontent.com/290288/108143076-19b47300-706b-11eb-8f82-c0f6a5af72ff.png">

## UI Issues

* The page is not yet converted to use `<PageLayout>` and `<HeaderPane>`
* Get rid of the drop down menu to go to other explorers. That's available in the navbar.
* Get rid of the "Suggest a new career goal" button. The user should be doing that from the page that lists all of the career goals, to ensure they don't suggest a career goal that already exists.
* Strange that "Students: 4" has no icons, but Faculty and Advisors do.  It could be mistaken for a bug. Use name and add image only if available?
* Add to Favorites button is broken.
* Add to Favorites -> Add to Profile

## UX Issues

* How do we communicate that this page is where you manage your profile interests?
* How do we build community from this page effectively?

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/h8r3QYXluSD59RyLhs3Han/RadGrad2---drilldown-pages?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="994" alt="Screen Shot 2021-04-07 at 1 27 36 PM" src="https://user-images.githubusercontent.com/290288/113946870-1903a780-97a5-11eb-8691-1d53c602033e.png">
