### ISSUE TITLE
Implement: Student Course Drilldown Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#412]
Please do work for this task in a branch called issue-412.

## Current design
<img width="1396" alt="Screen Shot 2021-02-17 at 10 46 01 AM" src="https://user-images.githubusercontent.com/290288/108265870-75373d00-710d-11eb-8600-d15d356d620e.png">

## UI Issues

* The page is not yet converted to use `<PageLayout>` and `<HeaderPane>`
* Get rid of the drop down menu to go to other explorers. That's available in the navbar.
* Not sure we need the "non-review" by Ophelia.
* Add to Favorites -> Add to Profile

## UX Issues

Not sure.

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/h8r3QYXluSD59RyLhs3Han/RadGrad2---drilldown-pages?node-id=0%3A1

**Comment by hannaparkUH** [comment]
Please see the updates. https://www.figma.com/file/0H3hRIjjgvBETqfXPshzhn/RadGrad2---community

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="1015" alt="Screen Shot 2021-04-07 at 1 29 05 PM" src="https://user-images.githubusercontent.com/290288/113946972-451f2880-97a5-11eb-9e18-3949b0fd4b30.png">

**Comment by cammoore** [comment]
Do we want to add an Edit button for Admins, Advisors, and Faculty to this page?

**Comment by philipmjohnson** [comment]
yes, both of those seem like a good idea.

**Comment by cammoore** [comment]
Didn't add the edit buttons. Going to create another issue for that.
