### ISSUE TITLE
Redesign: Student Opportunity Drilldown Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#413]
Please do work for this task in a branch called issue-413.

## Current Design

<img width="1435" alt="Screen Shot 2021-02-17 at 11 04 27 AM" src="https://user-images.githubusercontent.com/290288/108268005-08717200-7110-11eb-8f98-df9865b1a493.png">

## UI Issues
* The page is not yet converted to use `<PageLayout>` and `<HeaderPane>`
* Remove Suggest a New Opportunity button.
* Remove Explorers pulldown menu
* Add to Favorites -> Add to Profile

## UX Issues

Not sure.

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/h8r3QYXluSD59RyLhs3Han/RadGrad2---drilldown-pages?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Mockup complete:

<img width="1021" alt="Screen Shot 2021-04-07 at 1 30 17 PM" src="https://user-images.githubusercontent.com/290288/113947028-77c92100-97a5-11eb-969d-ab5829409955.png">

**Comment by cammoore** [comment]
Done.
