### ISSUE TITLE
Debug FavoriteCareerGoals error

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#416]
Please do work for this task in a branch called issue-416.

If you login as abi@hawaii.edu, you will find that she has no FavoriteCareerGoals, and you will further find that if you try to add a new FavoriteCareerGoal by pressing the "Add to Favorites" button, it is not added, even though the "Success" modal window pops up. 

I have spent a little time trying to understand this behavior, and here is what I have learned so far:

First, the default fixture does define three favorite career goals for abi@hawaii. These do not appear in the UI.  They do exist when you connect to the server-side MongoDB:

<img width="1160" alt="Screen Shot 2021-02-18 at 7 46 18 AM" src="https://user-images.githubusercontent.com/290288/108398707-6ad47c00-71bd-11eb-8430-cef8add512f0.png">

Second, the subscriptions for Favorite collections are weird, in that some client-side collections in MiniMongo have only the documents associated with that user (which seems like the correct behavior), while others have lots of documents for other users:

<img width="252" alt="Screen Shot 2021-02-18 at 7 48 58 AM" src="https://user-images.githubusercontent.com/290288/108399036-c7d03200-71bd-11eb-9833-a28758b44b96.png">

In particular, FavoriteCareerGoal and FavoriteInterest have 80 and 77 documents, while FavoriteCourse and FavoriteOpportunity only have 1. 

Finally, I notice that in these collection definitions, some refer to "userID" while others refer to "studentID", and that the default publications differ with respect to find with "share" vs find with "studentID". 

My hypothesis is that the publication methods for FavoriteCareerGoal and FavoriteInterest collections have a bug.

**Comment by cammoore** [comment]
The issue was a combination of the FavoriteCareerGoal publication only publishing { share: true } and when we created a FavoriteCareerGoal we default share to false. Updated the publication so students can see their own career goals even if they don't share.

Faculty have favorite career goals and interests they share theirs by default. Faculty don't have favorite courses or opportunities.
