### ISSUE TITLE
Redesign: Student Home Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#417]
Please do work for this task in a branch called issue-417.

## Current Design

<img width="1043" alt="Screen Shot 2021-02-20 at 2 06 50 PM" src="https://user-images.githubusercontent.com/290288/108611726-5ba02a80-7385-11eb-9b6c-f5be6a88c4ad.png">

## UI Improvements

* Contrast of text and background colors needs improvement.
* Make background color for each section continuous.

**Comment by cammoore** [comment]
Done
