### ISSUE TITLE
Redesign Career Goal/Interest relationship

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#420]
Please do work for this task in a branch called issue-420.

## The problem with Interests

Currently, Career Goals and Interests have a complex relationship which is difficult for explain to students.  I will call Interests added manually by students through the Interest Explorer "explicit" Interests, and Interests that are associated with students through adding a Career Goal "implicit" interests. 

Here are some of the behaviors associated with our current implementation which "tightly couples" Interests and Career Goals:

* A student can add or delete "explicit" interests one by one using the Interest Explorer.
* When a student adds a Career Goal, their profile is augmented with "implicit" Interests.
* Unlike explicit Interests, implicit Interests are "all or nothing". A student cannot delete implicit interests individually. They must delete the Career Goal to get rid of any of them, and that gets rid of all of them.
* Because of this difference between "explicit" and "implicit" interests, we often need to display them separately in the UI.

## A possible solution

We could instead "loosely couple" Interests and Career Goals.  

* When you add a Career Goal, the system can "recommend" some Interests to add.  
* When you delete a Career Goal, the system can prompt you to see if you want to keep or remove the corresponding Interests. 
* All Interests can be managed individually in the Interest Explorer.  
* This simplifies the UI.  We no longer need to display two types of Interests. 
* I believe "loose coupling" simplifies the conceptual model of Interests for students. 

## Implementation Notes

At least the following sections of the system need to be changed:

* When adding a Career Goal, a dialog box should pop up to ask which of the recommended interests should be added. If an Interest already exists in the student profile, it should not be listed.
* When removing a Career Goal, a dialog box should pop up to ask if the associated Interests should be deleted. The user can approve or decline each individually.
* UI pages listing interests can now delete the section listing Career Goal interests.
* The convert script must be modified to find the Interests associated with Career Goals for a given student, and add them to their "explicit" Interests list.

**Comment by cammoore** [comment]
Some of the tasks involved are:

* [ ] Change Users.getInterestIDs to not combine the interests from career goals.
* [ ] Remove the Users.getInterestIDsByType method.
* [ ] Create a button for the admin to update the existing users' interests. We'll only need to do this once.
* [ ] Create a AddCareerGoalToProfileButton that is similar to FavoritesButton. Has dialog boxes for adding/removing interests associated with the career goal.
* [ ] Rename FavoritesButton to AddToProfileButton.

**Comment by cammoore** [comment]
Done. We might want to look at the AddCareerGoalToProfileButton and tweak the UI.
