### ISSUE TITLE
Provide an auto-updated lastUpdate field for all documents. 

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#425]
Please do work for this task in a branch called issue-425.

To support checklists, many collections need to have a lastUpdate field. Please update these collections to support auto-update. It appears that the Collection2 package has support for this:

https://github.com/Meteor-Community-Packages/meteor-collection2#autovalue

Perhaps we can add this to BaseCollection and provide this to all of our documents by default?

Also need to update the convert script for RadGrad1 to add the current timestamp to these documents.

**Comment by cammoore** [comment]
We can't save the values in the database dump, but I think that is ok.
