### ISSUE TITLE
Review: Interest Explorer Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#426]
## Overview

Rashmi has finished an initial version of the Interest Explorer page following [Issue 397](https://github.com/radgrad/radgrad2/issues/397). 

Since this code will form a model for implementation of the Career Goal, Opportunity, and Course Explorers, it is important for us all to review it and determine if there are any opportunities for improvement before moving forward. 

Concerns:

* The "Sort By" controller is left-justified, not right justified. Rashmi tried for a little while to right justify it, without success. Do we care? Is it actually better left-justified?

## Review Branch

https://github.com/radgrad/radgrad2/tree/review-426

## Files to review

* https://github.com/radgrad/radgrad2/blob/review-426/app/imports/ui/pages/shared/browser-view/InterestBrowserViewPage.tsx

* https://github.com/radgrad/radgrad2/blob/review-426/app/imports/ui/components/shared/explorer/browser-view/InterestBrowserView.tsx

## Checklists

* [Architecture](https://www.radgrad.org/docs/developers/checklists/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/checklists/design-checklist)
* [User Interface](https://www.radgrad.org/docs/developers/checklists/ui-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/checklists/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/checklists/react-checklist)

## Due date

Friday, March 12, 3:30pm (the Friday RadGrad2 meeting)

## For more information

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by hannaparkUH** [comment]
Need to increase the size of the button "Suggest a new interest".
Need to increase the description font size.
Need to add more paddings.
Need to add the gray background?

**Comment by jatinp101** [comment]
Architecture Checklist -> looks good
Design -> looks good 
UI -> Mobile displays the desktop version, error in the console
JS/TS -> Change lodash filter to ES6 filter
React -> looks good

**Comment by philipmjohnson** [comment]
## From review of the rendered page

* The first line of the interest description is always slightly indented (due to a text-indent of 4px).  Let's get rid of that indentation; it's inconsistent with the rest of the system

## InterestBrowserViewPage.tsx

* L4: delete line with commented out import of lodash. It is imported three lines later!

* L35-42: Get rid of `<Grid>` and `<Grid.Row>`. They don't do anything.

* L66: Why compute 'interests'? It is never used!

## Meta comment

We really aren't supposed to put our comments in until the start of the review meeting.

**Comment by cammoore** [comment]
InterestBrowserViewPage.tsx

JS L4 extra commented out line remove

Design-08 L51 - 62 This code is probably very similar to the other
pages. We might want to create a function in the utilities directory
to do this work. We can pass in the name of the key we are interested
in checking.

React-04 L14 Shouldn't the import be InterestBrowserView?

InterestBrowserView.tsx

TS L19 Should this be typed as interestSortKeys?

L40 We should have a default sort.

L61, 62 Should we use the InterestChecklist to get the state and text for
this?


Should we update REACT-04: to say something the default import should
match the filename?
