### ISSUE TITLE
Implement standard "labels" for Courses, Career Goals, Opportunities, and Interests.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#431]
Please do work for this task in a branch called issue-431.

For users, we now have the idea of a "ProfileLabel", a standard way of presenting a user within the UI. It has a standard behavior when clicked (pop up a modal with more details for the user).

We need the same sort of abstraction for Opportunities, Interests, Career Goals, and Courses.

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/g0xnzLnAvL3j4iRi0JxAxQ/RadGrad2---labels-Courses%2C-Career-Goals%2C-Opportunities%2C-and-Interests.

**Comment by philipmjohnson** [comment]
## Mockup complete:

<img width="397" alt="Screen Shot 2021-03-22 at 11 15 40 AM" src="https://user-images.githubusercontent.com/290288/112059538-0c722480-8b00-11eb-9d23-564b2602b9d1.png">
