### ISSUE TITLE
Implement Faculty Home Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#436]
Please do work for this task in a branch called issue-436.

The Faculty Home Page currently looks like this:

<img width="1371" alt="Screen Shot 2021-03-18 at 9 43 23 AM" src="https://user-images.githubusercontent.com/290288/111687577-83d94880-87ce-11eb-8161-2d9d4b16c7fd.png">

To implement it, follow the design of the Student Home Page. The difference is the set of Checklist Items. 

Faculty checklist items that are already implemented include:

  * Terms and Conditions
  *  Interests (must specify some)
  * Career Goals (must specify some)
  * Privacy (should review periodically)

But for this issue, you will need to implement some new ones:

  * ManageOpportunities (periodically check the manage-opportunities page to see if the opportunities you own should be updated).
  * ManageVerificationRequests (if there are pending verification requests, process them)
  * ManageReviews (if there are pending reviews, process them)
  * ReviewCareerGoals (also Interests): Periodically check to see if there should be new Career Goals or Interests, and/or update the descriptions of existing ones. 

Once you are done implementing this page, take a step back and see if you can refactor out commonalities between the Student Home Page and this Faculty Home Page.

**Comment by cammoore** [comment]
There might be an opportunity to refactor the Checklists. There are last visited checklists that only depend on visiting a page. We might want to create a LastVisitedChecklist that takes a few strings.

I created a shared `<HomePageChecklistSegment okItems reviewItems improveItems />`.
Advisor, Faculty, and Student Home Pages use it.
