### ISSUE TITLE
Implement Faculty Privacy Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#437]
Please do work for this task in a branch called issue-437.

The Faculty Privacy Page currently looks like this:

<img width="1129" alt="Screen Shot 2021-03-18 at 10 11 38 AM" src="https://user-images.githubusercontent.com/290288/111691455-6c03c380-87d2-11eb-8500-b781ad0d67f8.png">

For this task, you will adapt the Student Privacy Page once it is implemented.  Once implemented, it should look similar to this:

<img width="1034" alt="Screen Shot 2021-03-05 at 10 24 15 AM" src="https://user-images.githubusercontent.com/290288/110169788-4a034d80-7d9d-11eb-878e-cb00fafd6fba.png">

Note that the principal differences between the Faculty privacy page and the student privacy page is that Faculty don't have Courses, Opportunities, ICE, or Levels to make public, so these should not appear as options.

Once implemented, consider ways to refactor to reduce duplicate code between this page and the Student Privacy Page.  Also, note that the Admin and Advisor privacy pages will be the same as this one.

**Comment by cammoore** [comment]
By default Advisors, Admin, and Faculty share their information. They can turn this off by using the VisibilityPage.
