### ISSUE TITLE
Implement: Manage Opportunities Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#439]
Please do work for this task in a branch called issue-439.

Faculty, advisors, and the admin all have a manage opportunities page. A portion of it currently looks like this:

<img width="1108" alt="Screen Shot 2021-03-18 at 10 24 26 AM" src="https://user-images.githubusercontent.com/290288/111692972-234d0a00-87d4-11eb-9147-55b856f9ec18.png">

There are a few opportunities for improvement:

* Somehow the page feels very long and hard to understand. Perhaps the various operations (Add, Your Opps, All Opps) could be in separate tabs?
* Perhaps the "Update" button could pop up a modal? Currently, clicking the button appears to have no effect if you have scrolled past the top part of the page. This will only get worse if we use tabs.
* The Logo field doesn't have a label.

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/FTfAUsn68AenIMBzqKns05/RadGrad2---advisor-opportunity-update?node-id=0%3A1

**Comment by philipmjohnson** [comment]
Mockups complete:

<img width="939" alt="Screen Shot 2021-04-07 at 2 23 56 PM" src="https://user-images.githubusercontent.com/290288/113950419-faa1aa00-97ac-11eb-8705-0e4790b8a02e.png">


<img width="923" alt="Screen Shot 2021-04-07 at 2 24 03 PM" src="https://user-images.githubusercontent.com/290288/113950426-00978b00-97ad-11eb-9245-9ab2e40476b9.png">

**Comment by philipmjohnson** [comment]
I have an idea for a much different approach to "management" of entities (Career Goals, Interests, Opportunities, Course) for Faculty and Advisors. 

Instead of trying to mimic the "Data Model" approach, why not just add an "Edit" button to the Details page associated with a specific entity when the user has the role Faculty or Advisor? Clicking that button pops up a modal that allows the user to edit certain fields. When they click submit, they are returned to that page which instantly reflects the new contents. 

We can also have an "Add" button on the Browser pages to create entirely new ones. 

For the time being, only an Admin can delete entities. 

I think this is actually easier to implement, and provides a better UX since users are seeing the entity in context, modifying it, and then seeing it in context again.

**Comment by cammoore** [comment]
Added the Edit and Delete buttons so the sponsors can manage their opportunities.
Have the EditOpportunityButton and DeleteOpportunityButton. We will add these buttons to the detail opportunity page when they are reimplmented.
