### ISSUE TITLE
Utilize event date for Opportunities

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#440]
Please do work for this task in a branch called issue-440.

Opportunities support an Event Date, but we don't actually use it in practice. 

This could be a useful addition to the Community Page by highlighting upcoming Opportunities (in the next, say, four months).

**Comment by cammoore** [comment]
What is the event date for a club?

**Comment by philipmjohnson** [comment]
Not all Opportunities will have an event, but many can and we don't take advantage of that right now.

**Comment by cammoore** [comment]
Closed via #413
