### ISSUE TITLE
Implement: Advisor student update page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#444]
Please do work for this task in a branch called issue-444.

## Current page

<img width="1442" alt="Screen Shot 2021-03-22 at 11 43 57 AM" src="https://user-images.githubusercontent.com/290288/112062729-683eac80-8b04-11eb-8bcf-99d659c3549f.png">
<img width="1442" alt="Screen Shot 2021-03-22 at 11 44 09 AM" src="https://user-images.githubusercontent.com/290288/112062765-77bdf580-8b04-11eb-9746-64685654d451.png">

Here are problems with this page:

1. Displaying 400+ students this way takes up way too much vertical space. Ideas: use profile labels? Have tabs for A-F, G-H, etc? 

2. The "update" panel appears when you click on a label, but it is often not visible in the page when displayed so you don't know that it happened.

3. Is it good to have to click to see the student's degree plan? How about displaying it directly in this page? Plus their interests and career goals? 

4. We no longer have an advisor log.

**Comment by hannaparkUH** [comment]
https://www.figma.com/file/L2DQ0woHiQxlrePnwwU1Em/RadGrad2---advisor-student-update

**Comment by philipmjohnson** [comment]
Mockups complete:

<img width="328" alt="Screen Shot 2021-04-08 at 7 55 21 AM" src="https://user-images.githubusercontent.com/290288/114074321-f5da0600-983f-11eb-9465-7421c7c84dcd.png">

<img width="324" alt="Screen Shot 2021-04-08 at 7 55 28 AM" src="https://user-images.githubusercontent.com/290288/114074353-fe324100-983f-11eb-810e-76fa9472449e.png">


<img width="316" alt="Screen Shot 2021-04-08 at 7 55 34 AM" src="https://user-images.githubusercontent.com/290288/114074374-025e5e80-9840-11eb-8e1d-4163157c14e6.png">

<img width="310" alt="Screen Shot 2021-04-08 at 7 55 40 AM" src="https://user-images.githubusercontent.com/290288/114074396-08543f80-9840-11eb-8be4-7d6fc69bc9bb.png">

**Comment by cammoore** [comment]
Done.
