### ISSUE TITLE
Review and improve RadGrad Semantic UI Color Palette

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#445]
## About the Semantic UI Color Palette

Many Semantic UI elements accept a color attribute which must be one of the following strings: 'red', 'orange', 'yellow', 'olive', 'green', 'teal', 'blue', 'violet', 'purple', 'pink', 'brown', 'grey', and 'black'.

Currently, the custom semantic ui theme that we build results in the following choices:

<img width="393" alt="Screen Shot 2021-03-24 at 10 21 49 PM" src="https://user-images.githubusercontent.com/290288/112442536-05aa0400-8cf0-11eb-805f-91669acfb469.png">

These theme colors are specified here: https://github.com/radgrad/fomantic-ui/blob/main/semantic/src/site/globals/site.variables

Note that we have not overridden all of the colors, just a subset. This makes the current set of color choices potentially incompatible when viewed together. 

## Task 1: Determine the actual color palette used in RadGrad

A simple search in IntellliJ through the ui/ subdirectory tree for all (case-insensitive) matches of "color:" shows that there are dozens of times where the built-in color palette is ignored and a hex color value is used instead:

<img width="1318" alt="Screen Shot 2021-03-26 at 8 58 18 AM" src="https://user-images.githubusercontent.com/290288/112680951-1e123f80-8e12-11eb-80c0-e17bb518465a.png">

So, the first task is to research what the RadGrad Color Palette is "in practice": what are we actually using?

## Task 2: Revise the Semantic UI Color Palette

Based on this research, determine if improvements can be made to the built-in colors in order to better reflect the actual color palette.

## Task 3: Implement a standard approach to obtaining colors 

As the IntelliJ search reveals, there many duplicate occurrences of a color string.  For example:

<img width="789" alt="Screen Shot 2021-03-26 at 9 07 38 AM" src="https://user-images.githubusercontent.com/290288/112681425-cde7ad00-8e12-11eb-8800-1916960ff4ff.png">

We should set this color value one place in the code, and import it as a variable and reference it rather than have 18 copies of the same string scattered around the code base.  The benefit of standardizing color access is that we can change the color palette by changing one place and have it reflected throughout the code body.

Note that this standard approach will probably involve making it possible to access the Semantic UI color palette through variables.  This is because we may at times want to use a Semantic UI theme color in a context where a color parameter is not available. That's OK. It just means that for certain colors, if we want to change them, we have to update them in two places: the Semantic UI theme definition, and the standard color definitions within the code base.

**Comment by hannaparkUH** [comment]
Philip, I guess that we have already set the customized colors in the site.variable file. 

/* Color Palette */
@radgrad-white             : #ffffff;
@radgrad-softGrey          : #f7f7f7;
@radgrad-yellow            : #CEB23F;
@radgrad-defaultGrey       : rgba(0,0,0,.4);
@radgrad-dimGrey           : #696969;
@radgrad-radGreen          : #6FBE44;
@radgrad-radGreen-darken   : #38840F;
@radgrad-seaGreen          : #86CAB5;
@radgrad-seaGreen-darken   : #53A78E;
@radgrad-seaGreen-darken-1 : #1B7F61;
@radgrad-orangeYouRad      : #DA7F4E;
@radgrad-lightOrange       : #C05E2A;
@radgrad-roseRed           : #CA4864;

/* Inject the palette into the Semantic UI theme. */
@green            : @radgrad-radGreen;
@red              : @radgrad-roseRed;
@lightgreen       : lighten(@radgrad-radGreen, 5);
@olive            : darken(@radgrad-radGreen, 5);
@blue             : @radgrad-seaGreen-darken;
@lightblue        : @radgrad-seaGreen;
@yellow           : @radgrad-yellow;
@orange           : @radgrad-orangeYouRad;
@grey             : @radgrad-defaultGrey;

**Comment by philipmjohnson** [comment]
@hannaparkUH Yes, I know that some of them are set. 

Two questions:

1. What about the colors that aren't set?  Should we set them too to something compatible?
2. Are these the right colors?  When I make the color of a label "green", is it the right "green"?

**Comment by hannaparkUH** [comment]
Philip, the grey color needs to be changed. I added the olive . Please add the following code to the site.variables. 
@grey             : @radgrad-dimGrey;
@olive            : @radgrad-radGreen-darken;

**Comment by hannaparkUH** [comment]
![image](https://user-images.githubusercontent.com/53065327/112700559-883adc80-8e32-11eb-863b-abb760e4b537.png)
This color palette would be helpful for developers.

**Comment by philipmjohnson** [comment]
Thanks @hannaparkUH. Let's go a little farther, and make it clear how we are overriding all of the built-in colors.  So, what I want is to be able to update site.variables to include two sections:

```
/* RadGrad Color Palette */
@radgrad-red: ???;
@radgrad-orange: ???;
@radgrad-yellow: ???;
@radgrad-olive: ???;
@radgrad-green: ???;
@radgrad-teal: ???;
@radgrad-blue: ???;
@radgrad-violet: ???;
@radgrad-purple: ???;
@radgrad-pink: ???;
@radgrad-brown: ???;
@radgrad-grey: ???;
@radgrad-black: ???;
```

Once we have values for each of these, then we override the semantic ui palette with this:

```
/* Make the Semantic UI Palette correspond to the RadGrad Palette. */
@red: @radgrad-red;
@orange: @radgrad-orange;
@yellow: @radgrad-yellow;
@olive: @radgrad-olive;
@green: @radgrad-greeen;
@teal: @radgrad-teal;
@blue: @radgrad-blue;
@violet: @radgrad-violet;
@purple: @radgrad-purple;
@pink: @radgrad-pink;
@brown: @radgrad-brown;
@grey: @radgrad-grey;
@black: @radgrad-black;
```

You may find after reviewing all occurrences of the colors used in the system that other color definitions are required in addition to these.  That's fine, add them too. But these are the required ones.

**Comment by hannaparkUH** [comment]
@radgrad-red: #CA4864;
@radgrad-orange: #DA7F4E;
@radgrad-yellow: #CEB23F;
@radgrad-olive: #38840F;
@radgrad-green: #6FBE44;
@radgrad-blue: #53A78E;
@radgrad-grey: #696969;
@radgrad-purple: #952263;
@radgrad-pink: #DDA1C3;
@radgrad-teal: ???;
@radgrad-violet: ???;
@radgrad-brown: ???;
@radgrad-black: ???;

I think we don't need the modify the colors for teal, violet, brown and black.  f you want, I can get those hex color values from the semantic ui theme.  Let me know.

**Comment by hannaparkUH** [comment]
@philipmjohnson 
I have found the following unspecified color values.  Please update them.

#F7F7F7 - @radgrad-softGrey
#F2F2F2 - @radgrad-softGrey
#7CC154 - @radgrad-green
#2F9276 - @radgrad-olive
#348C72 - @radgrad-blue
rgba(255,255,255,.7)- @radgrad-white
rgba(0,0,0,.8) - @radgrad-black
rgb(79, 168, 143, 0.80) - @radgrad-blue

**Comment by hannaparkUH** [comment]
![image](https://user-images.githubusercontent.com/53065327/113052149-7fa01a00-9142-11eb-8fee-1c973c8e4bc8.png)

**Comment by philipmjohnson** [comment]
OK, but because I want to list colors in alphabetical order, I will rename them so that the primary color comes first.

For example, instead of @radgrad-softgrey, it will be @radgrad-grey-soft

**Comment by philipmjohnson** [comment]
Now that we have the Color Palette defined, we want to eliminate all hard-coded references to hex colors.  Here's how to proceed:

## Create a branch off master called issue-445

You will do all your work in this branch.

## Search for all occurrences of color:

To start looking for hex values, you can use IntelliJ to search for all occurrences of the string "color" in the ui/ subdirectory:

<img width="789" alt="Screen Shot 2021-03-30 at 1 34 40 PM" src="https://user-images.githubusercontent.com/290288/113069735-b3883900-915c-11eb-9df4-d4c19c28e389.png">

## Or find a color to work on

Another way is to pick a hex value and search for it:

<img width="789" alt="Screen Shot 2021-03-30 at 1 26 19 PM" src="https://user-images.githubusercontent.com/290288/113069811-d61a5200-915c-11eb-883f-de56292d0469.png">

## Now edit a file containing hex values

Now select a file to work on. For example, landing-styles.ts:

<img width="1598" alt="Screen Shot 2021-03-30 at 1 26 53 PM" src="https://user-images.githubusercontent.com/290288/113069897-06fa8700-915d-11eb-9caf-95e462bb9e93.png">

## Import the COLORS object into the file:

We need to import the COLORS object:

<img width="1598" alt="Screen Shot 2021-03-30 at 1 38 28 PM" src="https://user-images.githubusercontent.com/290288/113069979-42955100-915d-11eb-9da4-80b83dc17492.png">

## Replace a hex (or rgba) value with its existing COLORS value:

So, `rgba(0,0,0,.8)` corresponds to COLORS.BLACK, so replace it:

<img width="1598" alt="Screen Shot 2021-03-30 at 1 40 31 PM" src="https://user-images.githubusercontent.com/290288/113070110-84be9280-915d-11eb-8f47-018f300639d1.png">

## Replace a "rogue" color with its closest counterpart from our color palette

The next hex value in the file, `#7CC154`, is not in our palette. You can easily figure this out by looking at the [Colors documentation page](https://www.radgrad.org/docs/developers/patterns/colors). 

In this case, you want to find a "close" color.  An easy way is to paste the hex value into Google, which shows the color:

<img width="785" alt="Screen Shot 2021-03-30 at 1 30 25 PM" src="https://user-images.githubusercontent.com/290288/113070243-d5ce8680-915d-11eb-855d-b18c382672c5.png">

Comparing this page to the Color Palette in the documentation shows that this color is almost exactly the same as COLORS.GREEN.  So, make the replacement:

<img width="1598" alt="Screen Shot 2021-03-30 at 1 31 14 PM" src="https://user-images.githubusercontent.com/290288/113070303-f991cc80-915d-11eb-945d-0e9169dfe985.png">

## Run the system and check to see that the page still looks OK

After you've made changes to a file, run the system (`meteor npm run start`), retrieve the page containing your changes, and check to see that the colors still look OK.

## Propose additions to our color palette if necessary

If you run across a color that needs to be in our palette, send a proposal to the #radgrad2-chat list.

## Commit your changes into master regularly.

At regular intervals (every 3-4 days max), merge master into your branch, make sure all tests pass, then merge your branch into master.  That way, others can pick up your changes incrementally and we aren't faced with a lot of merge conflicts all at once.

**Comment by hannaparkUH** [comment]
@philipmjohnson I've updated the most of the hex and rgba color values  in the tsx and ts files. Please the review them.
