### ISSUE TITLE
Course and Opportunity Profile Collections do not correctly represent user state

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#446]
Please do work for this task in a branch called issue-446.

While working on the entity label design, I discovered that adding a course or opportunity to one's profile does not update the corresponding Profile collection, and so the corresponding entity label will not be colored appropriately.  For example, after bringing up the development fixture, I added ICS 101 and Hawaii Hacker Hours to the profile for abi@hawaii.edu:

<img width="1351" alt="abi-hawaii-hacker-hours" src="https://user-images.githubusercontent.com/290288/112542799-16db2b00-8d59-11eb-9db5-afe53bbbdb86.png">

<img width="1392" alt="abi-ics-101" src="https://user-images.githubusercontent.com/290288/112542847-22c6ed00-8d59-11eb-9d61-08b45a633f32.png">

However, going to the privacy page (which currently displays sample labels) shows that ICS 101 and Hawaii Hacker Hours are colored grey, not green, indicating that they were not found in the corresponding Profile collection:

<img width="1209" alt="abi-privacy" src="https://user-images.githubusercontent.com/290288/112542987-49852380-8d59-11eb-835f-e937c271d676.png">

**Comment by cammoore** [comment]
The profile entity collections don't all use userID to identify the profile. For courses and opportunities, we use studentID, not userID.
Do we want faculty and advisors to have profile courses and opportunities?

We can fix this in two ways, update the Course and Opportunity labels or update the profile entity collections to all use userID.

**Comment by philipmjohnson** [comment]
It's OK to leave it as a studentID.  BTW, sorry for being dense, but what is a studentID? is that the docID of the corresponding StudentProfileCollection document?

**Comment by cammoore** [comment]
Each profile has an userID field that is the Meteor.userId.
In the ProfileCourse and ProfileOpportunity collections, we store courseID/opportunityID and studentID. The studentID is the StudentProfile.userID. 

I wanted it to be clear that non-students shouldn't have any ProfileCourses or ProfileOpportunities.
