### ISSUE TITLE
Remove StudentParticipations

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#454]
Please do work for this task in a branch called issue-454.

Upon startup, there is an invocation of a StudentParticipations cron job:

```
SyncedCron: Scheduled "Run StudentParticipations.upsertEnrollmentData" next run @Thu Apr 01 2021 00:00:00 GMT-1000 (Hawaii-Aleutian Standard Time)
```

We should delete StudentParticipations and all associated references:

<img width="910" alt="Screen Shot 2021-03-31 at 11 21 24 AM" src="https://user-images.githubusercontent.com/290288/113213025-44215080-9213-11eb-8cbd-e7b8c8683d15.png">

Note this also means that we should make sure that the convert script for RadGrad1 to RadGrad2 does not convert student participation data.

**Comment by cammoore** [comment]
Had to create a new Validated Method for getting ProfileOpportunities.
