### ISSUE TITLE
Interest Page and Career Goals Page doesn't load first time after student logins, it works after page refresh.

### ISSUE THREAD

**Issue by RashmiAR** [radgrad/radgrad2#457]
Please do work for this task in a branch called issue-XXX.
1. Currently the issue occurs in branch called issue-398.
2. This issue came up after we removed the Duplicate code in with Tracker from explorer pages(Interess and CareerGoals)
3. Clear cookies, do Meteor reset and then run RadGrad website to reproduce error.
4. The issue occurs when we make a call to getProfile of user in the WithTracker( profile = Users.getProfile(username); )
![NoProfileFound](https://user-images.githubusercontent.com/54429784/113796681-86530200-96eb-11eb-9739-b8f36d3e5e01.png)

**Comment by cammoore** [comment]
I can't reproduce this bug. Am going to close.
