### ISSUE TITLE
A script to convert RadGrad1 database dump to RadGrad2.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#46]
Please do work for this task in a branch called issue-46.

We are going to need a script that converts RadGrad1 database dump files to a format that RadGrad2 can load.

**Comment by gcalica** [comment]
With this script, we should also tackle this problem: https://github.com/radgrad/radgrad2/issues/4#issuecomment-499270848

**Comment by cammoore** [comment]
I just pushed this branch to master. The script makes the relative links absolute for the career goals. Didn't take a look at the help messages.
