### ISSUE TITLE
Migrate Favorite* Collections to Profile* Collections

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#462]
Please do work for this task in a branch called issue-462.

The Community page in radgrad2.ics.hawaii.edu displays bogus data for Most Popular Interests, Career Goals, and Opportunities:

<img width="1311" alt="Screen Shot 2021-04-13 at 10 19 28 AM" src="https://user-images.githubusercontent.com/290288/114616905-23a9bb00-9c43-11eb-919c-a0f75ee85dd9.png">

This is apparently because this page uses "Profile" collections, and our existing data is based on "Favorite" collections:

https://github.com/radgrad/radgrad2/blob/master/app/imports/api/utilities/MostPopular.methods.ts

It appears to work correctly on a test fixture:

<img width="1311" alt="Screen Shot 2021-04-13 at 10 03 37 AM" src="https://user-images.githubusercontent.com/290288/114618725-65d3fc00-9c45-11eb-9dd0-16b95b68dba3.png">

So, we need to migrate the "Favorite" collections to Profile collections as part of the RaGrad1->RadGrad2 database conversion process.

Then we can reload this snapshot into the production database and all should be well.

**Comment by cammoore** [comment]
We should be ok the convert-dump script ignores the FavoriteCareerGoal and FavoriteInterest collections. All the profiles have an array of interest slugs and an array of career goal slugs. When we define a Profile the profile entity collections are updated.

**Comment by cammoore** [comment]
Done
