### ISSUE TITLE
2. Perform critical review of RadGrad as user

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#464]
An initial onboarding step for new RadGrad student developers is to perform a critical review of the system. This involves:

1. Logging in to the appropriate deployment of RadGrad.

3. Using your Home Page as guidance, take care of all "High" and "Medium" priority tasks on your To Do list.  Take careful notes during this process, possibly augmented by screenshots.  You want to identify both the strengths and weaknesses of the current interface.

4. Review any remaining pages and features not reviewed through step (3) above.

5. Write an essay for your professional portfolio called something like "A critical review of RadGrad".  This essay should be 5-10 pages and recount your experiences using RadGrad, and an enumeration of the top 3-4 strengths of RadGrad and the top 3-4 weaknesses.  Please conclude the essay with recommendations for what should be improved. These recommendations will be helpful in prioritizing future development work on the system. 

6. Post the URL to your essay as a comment to this issue.

**Comment by saitoshi** [comment]
Below is my essay for the critical review of RadGrad. 

https://saitoshi.github.io/radgrad_review.html

**Comment by trey-sumida** [comment]
[https://treysumida.com/projects/radgradreview](url)

**Comment by timothyhuo1** [comment]
https://timothyhuo1.github.io/essays/radgradreview.html

**Comment by ruizaj** [comment]
https://ruizaj.github.io/essays/radgrad.html

**Comment by CalianaFortin** [comment]
https://calianafortin.github.io/essays/A-critical-review-of-RadGrad.html
