### ISSUE TITLE
3. Review RadGrad tech stack

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#466]
This task is intended to help you become familiar with the RadGrad tech stack through a simple development exercise. 

First, review the basics of  RadGrad tech stack by following the instructions at [Getting Started: Tech Stack](https://www.radgrad.org/docs/developers/getting-started/tech-stack). 

Next, create a comment to this issue in which you detail which parts of the tech stack you are currently unfamiliar with.

**Comment by trey-sumida** [comment]
I have not worked with Typescript before, and only know that is a superset of Javascript so I will need to learn the basic syntax and differences between Typescript and Javascript. I also haven't used Uniforms before as well.

**Comment by saitoshi** [comment]
Similar to as Trey mentioned above while I have heard about TypeScript and Uniforms, I have not used them in depth before that I need to learn the syntax and more indepth details on both of them.

**Comment by ruizaj** [comment]
I haven't used Uniform before and I would most likely need to refresh myself about Meteor and Typescript again.

**Comment by timothyhuo1** [comment]
I have not used TypeScript and Uniforms before and I would need to look into them more.

**Comment by CalianaFortin** [comment]
I am currently unfamiliar with Typescript, so I would need some time to review it. I am familiar with uniforms and meteor, however I think it would be good for me to review these topics.
