### ISSUE TITLE
4. Download and install RadGrad

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#467]
Following the directions at [How to install RadGrad](https://www.radgrad.org/docs/developers/getting-started/howto/install-radgrad), download and install the system, [run the scripts](https://www.radgrad.org/docs/developers/getting-started/howto/run-scripts), and [run the tests](https://www.radgrad.org/docs/developers/testing/overview).

Once you done all that, please create a comment to this issue that includes the following:

1. A screenshot of your console window showing the system running.
2. A screenshot of the home page for your account. (The development fixture includes accounts for all four of you, though not with current degree experience data.)
3. A screenshot of the console window after having successfully run `meteor npm run test-all`.

**Comment by saitoshi** [comment]
<ol>
<li> A screenshot of our window with the application running.<br/>
![image](https://user-images.githubusercontent.com/47809066/118875655-48224280-b927-11eb-8ac8-0c737c42ed5d.png)

![image](https://user-images.githubusercontent.com/47809066/118875737-60925d00-b927-11eb-839a-b0091e58be8c.png)

<li> A screenshot of out homepage of our account.
<img width="1430" alt="RadGradHome" src="https://user-images.githubusercontent.com/47809066/118875359-ed88e680-b926-11eb-8f8b-071c6ea1b266.png">
<li> A screen shot after test all.
<img width="1792" alt="test-all 1" src="https://user-images.githubusercontent.com/47809066/118875556-25902980-b927-11eb-9263-8c6b1bb6aad9.png">
<img width="1773" alt="test-all 2" src="https://user-images.githubusercontent.com/47809066/118875895-91729200-b927-11eb-9e23-369bcd4c34b4.png">

</ol>

**Comment by ruizaj** [comment]
1. Console log of starting up RadGrad

![image](https://user-images.githubusercontent.com/60155925/118879780-d4cbf280-b88c-11eb-9e31-cad6e1779e85.png)

2. Homepage of my account

![image](https://user-images.githubusercontent.com/60155925/118879877-f036fd80-b88c-11eb-9b5a-34dabb06065b.png)

3. Running each test individually (since I'm still working out WSL)

lint
![image](https://user-images.githubusercontent.com/60155925/118879982-0a70db80-b88d-11eb-88ee-c8ee2261cd16.png)

test-unit
![image](https://user-images.githubusercontent.com/60155925/118880021-1492da00-b88d-11eb-9fef-6767bc1bcd09.png)

test-integration
![image](https://user-images.githubusercontent.com/60155925/118880036-1b215180-b88d-11eb-813a-2f06d896641f.png)

test-acceptance-development
![image](https://user-images.githubusercontent.com/60155925/118880061-22485f80-b88d-11eb-902a-41734d021514.png)

**Comment by timothyhuo1** [comment]
1. console window showing RadGrad running
<img width="699" alt="Screen Shot 2021-05-19 at 10 26 19 AM" src="https://user-images.githubusercontent.com/61216890/118884533-4d817d80-b892-11eb-983a-43d6d59ee3d0.png">

2. home page of my account
<img width="1440" alt="Screen Shot 2021-05-19 at 10 28 40 AM" src="https://user-images.githubusercontent.com/61216890/118884587-612ce400-b892-11eb-8770-1f752673594b.png">

3. console window after successfully running test-all
<img width="1050" alt="Screen Shot 2021-05-19 at 11 05 44 AM" src="https://user-images.githubusercontent.com/61216890/118884646-74d84a80-b892-11eb-8417-ca136797135b.png">

**Comment by trey-sumida** [comment]
RadGrad system running
![radgradconsole](https://user-images.githubusercontent.com/54917302/118886350-86baed00-b894-11eb-984c-ee98a8d8f4f3.png)

Homepage of my account
![radgradhomepage](https://user-images.githubusercontent.com/54917302/118886405-9cc8ad80-b894-11eb-90de-d19ded0ef311.png)

Console after successful test-all
![testall](https://user-images.githubusercontent.com/54917302/118886452-ab16c980-b894-11eb-9dbb-6cd048703f80.png)

**Comment by CalianaFortin** [comment]
### RadGrad system running
<img width="909" alt="Screen Shot 2021-05-21 at 12 20 14 AM" src="https://user-images.githubusercontent.com/70739998/119128083-e0c0cd00-b9d0-11eb-8a74-1a84ce5f30c5.png">

### My Homepage
<img width="1333" alt="Screen Shot 2021-05-21 at 12 23 55 AM" src="https://user-images.githubusercontent.com/70739998/119128114-eb7b6200-b9d0-11eb-83c4-516646b10b3f.png">

### Console after successful test-all
<img width="843" alt="Screen Shot 2021-05-21 at 1 06 32 AM" src="https://user-images.githubusercontent.com/70739998/119128136-f6ce8d80-b9d0-11eb-8e77-ad461534be20.png">
