### ISSUE TITLE
Review: Explorer Views

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#469]
## Overview

The goal of this review is to investigate the design patterns in use in newly created Explorer code and see if opportunities for additional improvement exist. 

## Review Branch

https://github.com/radgrad/radgrad2/tree/review-469

## UI to review

Before looking at the source code, please bring up the system in development mode and look at the Career Goal and Interest Explorer pages.

## Files to review

* https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/pages/shared/browser-view/CareerGoalBrowserViewPage.tsx

* https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/pages/shared/browser-view/InterestBrowserViewPage.tsx

* https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/components/shared/explorer/browser-view/BrowserView.tsx

* https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/components/shared/explorer/browser-view/SortWidget.tsx

## Checklists

* [Architecture](https://www.radgrad.org/docs/developers/checklists/architecture-checklist)
* [Design](https://www.radgrad.org/docs/developers/checklists/design-checklist)
* [User Interface](https://www.radgrad.org/docs/developers/checklists/ui-checklist)
* [JS and TS](https://www.radgrad.org/docs/developers/checklists/js-ts-checklist)
* [React](https://www.radgrad.org/docs/developers/checklists/react-checklist)
* [Testing](https://www.radgrad.org/docs/developers/checklists/testing-checklist)

## Due date

Friday, April 16, 3:30pm

## For more information

The review process is documented at: https://www.radgrad.org/docs/developers/reviews/overview

**Comment by philipmjohnson** [comment]
## CareerGoalBrowserViewPage

###  [L54](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/pages/shared/browser-view/CareerGoalBrowserViewPage.tsx#L54)

Under what conditions does Users.hasProfile(username) return
  false?

What should be done when that happens?

### [L54-L68](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/pages/shared/browser-view/CareerGoalBrowserViewPage.tsx#L54-L68)

updateLastVisitedMethod should be reimplemented:

https://github.com/radgrad/radgrad2/issues/475
  
### [L34-L36](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/pages/shared/browser-view/CareerGoalBrowserViewPage.tsx#L34-L36)

Three properties passed to component, but withTracker computes four properties (L76-L79).

You can eliminate careerGoals?

## InterestBrowserViewPage

### [L43-L57](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/pages/shared/browser-view/InterestBrowserViewPage.tsx#L43-L57)

https://github.com/radgrad/radgrad2/issues/475

## BrowserView.tsx

### [L34-L45](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/components/shared/explorer/browser-view/BrowserView.tsx#L34-L45)

You can eliminate the case statement. Change

`state.shared.scrollPosition.explorer.interests` to
   `state.shared.scrollPosition.explorer[ownProps.explorerType.toLowerCase()]`
   
and

`state.shared.cardExplorer.interests.sortValue` to
   `state.shared.cardExplorer[ownProps.explorerType.toLowerCase()].sortValue`

### L83, 85, 87, 89:

Please read the docs: https://eslint.org/docs/rules/no-case-declarations

You just need to add a block to the case to avoid this warning.

###  [L111 - L119](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/components/shared/explorer/browser-view/BrowserView.tsx#L111-L119)

Can be replaced with one line:

`const checklist = EXPLORER_TYPE.INTERESTS ? new
InterestsChecklist(currentUser) : new CareerGoalsChecklist(currentUser);`

### L134, L137

Does anyone reference these IDs? If not, remove them.

### L26:

This should be an enumerated type.

## High Level Comment: Enumerated types

Enumerated types are one of the biggest benefits of typescript. Let's
use them.  They are SO EASY TO USE.

https://www.typescriptlang.org/docs/handbook/enums.html

## High Level Comment: Is this the right UI design?

The current explorer page makes it very hard to distinguish in-profile
and not in-profile.

How about using a Label to represent in-profile entities, in a segment
that's a column? (Or in a row along the top?)

## SortWidget.tsx

### [L11-L21](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/components/shared/explorer/browser-view/SortWidget.tsx#L11-L21)

Use enum

### [L76-L91](https://github.com/radgrad/radgrad2/blob/review-469/app/imports/ui/components/shared/explorer/browser-view/SortWidget.tsx#L76-L91)

I don't think you need to go through the whole AutoForm thing for a single control that doesn't have a submit button.

The RadGradHeaderOptions doesn't use Redux to save the state of the controller globally, but otherwise accomplishes everything this special-purpose controller does.

Details at:

https://www.radgrad.org/docs/developers/patterns/sandbox#sandboxsegmentpage
https://github.com/radgrad/radgrad2/blob/master/app/imports/ui/pages/sandbox/SandboxSegment5.tsx

## High Level Comment: Naming standards

We no longer use "Widget", right?

**Comment by cammoore** [comment]
## CareerGoalBrowserViewPage.tsx

JS-06: L74 avoid _.filter

Design-08: L54 - 68 This code is very similar to L43 - L57 of
InterestBrowserViewPage.tsx. Can we consolidate to a utility function?

## InterestBrowswerViewPage.tsx

L42 `allInterests` is a misleading name.

JS-06: L62 avoid _.filter

## BrowserView.tsx

TS: L23 Why is items optional? Does this make sense?

TS: L26 Shouldn't explorerType be typed?

L74 Shouldn't this be closer to where it is used on L100, 104

L83 - L90 Can this be done out of the switch?

L130 Shouldn't the icon depend on the explorer type?

## SortWidget.tsx

Arch-01 Don't like the name of this component.

TS: L11 - 21 Should these be combined?

TS-01: L25 avoid any. ESLint suggests using never.

TS: L26 Shouldn't explorerType be typed?

**Comment by jatinp101** [comment]
Review 469

CareerGoalBrowserViewPage.tsx 

Looks pretty good: meets architecture checklist, meets design checklist, meets UI Checklist,
 JS-06: filter underscore not needed as there is a ES6 function that can handle that, 
REACT-06: change let to const for profile and careerGoals,
Passed the tests


InterestBrowserViewPage.tsx

Looks pretty good: meets architecture checklist, meets design checklist, meets UI Checklist, 
JS-06: filter underscore not needed as there is a ES6 function that can handle that,
REACT-06: change let to const for profile and careerGoals,
Passed the tests


BrowserView.tsx

Looks pretty good: meets architecture checklist, meets design checklist, meets UI Checklist,
 JS-06: sortby underscore not needed as there is a ES6 function that can handle that, meets react checklist,
Passed the tests



SortWidget.tsx

Looks good: meets architecture checklist, meets design checklist, meets UI Checklist,
 meets js/ts/css/eslint checklist, 
REACT 10: has "widget" in its name but not a big deal as it helps with the naming,
Passed the tests
