### ISSUE TITLE
RadGrad2 Degree Planner page broken with latest snapshot

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#470]
Please do work for this task in a branch called issue-470.

When logged in as OPQ on radgrad2, retrieving the degree planner page yields:

<img width="1065" alt="Screen Shot 2021-04-14 at 1 25 15 PM" src="https://user-images.githubusercontent.com/290288/114792931-01886980-9d25-11eb-9ff0-9dafa209c4d6.png">

**Comment by cammoore** [comment]
Fixed
