### ISSUE TITLE
Stop subscribing to Forecast collections?

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#471]
Please do work for this task in a branch called issue-471.

Inspection of the collections in radgrad2 reveals that there are a total of 5752 entries, of which 1870 (32%) are from the Forecast collections:

<img width="1484" alt="Screen Shot 2021-04-14 at 1 54 36 PM" src="https://user-images.githubusercontent.com/290288/114794895-12d37500-9d29-11eb-84b5-7d213660f90b.png">

Specifically:

* 992 (CourseForecast)
* 611 (OpportunityForecast)
* 105 (ProfileCoursesForecast)
* 72 (ProfileInterestsForecast)
* 18 (ProfileCareerGoalsForecast)
* 72 (ProfileInterestsForecast)

Since Forecasts are only occasionally needed, can we use a Meteor Method to obtain Forecast data when necessary and reduce our pub/sub overhead by a third?

**Comment by cammoore** [comment]
Removed Course and Opportunity ForeCastCollections.

Need to see where the Profile Forecast collections are used.

**Comment by cammoore** [comment]
Done
