### ISSUE TITLE
Create Summer 2021 Onboarding Programming task

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#472]
Please do work for this task in a branch called issue-472.

Create a page with segments that exercise important RadGrad data/display issues.

* Display a new page (update router, create page in correct directory, use PageLayout).

Then, use RadGradSegments and RadGradHeader to display:
* static text
* username
* MiniMongo data manipulated in standard ways. 
* Entity Labels.
* A form that returns minimongo data when submit is pressed
* A form with a controller that immediately updates segment contents.
* A Meteor Method to do something.

**Comment by cammoore** [comment]
* Add a Tabbed component.
