### ISSUE TITLE
Re-design UserInteractions and Feeds

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#482]
Please do work for this task in a branch called issue-482.

## The Problem: Overview

Historically, "Feeds" and "UserInteractions" were implemented entirely independently and during a time where we didn't understand clearly what kinds of information about RadGrad usage was important to gather, analyze, and retain. As a result, the current implementation suffers from the following problems:

1. Redundancy.  Feeds and UserInteractions record many of the same kinds of information. 
2. Complexity. The Feeds implementation is quite complicated and brittle.
3. General weirdness in where code to implement these features are located in the system. For example, [profile-button.ts](https://github.com/radgrad/radgrad2/blob/master/app/imports/ui/components/shared/explorer/item-view/utilities/profile-button.ts) contains a bunch of complicated code for defining what seem to be quite simple user interactions, and is located nowhere near the UserInteraction collections or their UI analyses.

The goal of this task is to create a simple, easy to understand, unified mechanism for:

1. Instrumenting user interactions with the system via a single mechanism.
2. Providing "community" information about user behavior that answers the question: "What's new?". This involves a component in the Community page that lists recent activity in the system, and which respects current visibility settings by users. 
3. Providing "researcher" information about user behavior. This involves an administrator-level analysis that produces actionable classifications of student behaviors.

## The Problem: RadGrad1's design

The RadGrad1 design involves two Collections with overlapping functionality: Feed and UserInteractions.

### RadGrad1's FeedCollection: Supporting "What's New?"

The FeedCollection was implemented as a way to provide community with insight into recent activities by users. Put simply, Feeds are supposed to indicate "What's New?" We wanted to help users obtain a sense for what was going on in RadGrad, and notify them of updates and additions to the system.

The FeedCollection tries to accomplish this by defining the following types of activities:
  * New User
  * New Course
  * New Opportunity
  * New Verified Opportunity
  * New Course Review
  * New Opportunity Review
  * New Level

Interestingly, RadGrad1's Feed Collection never supported new Interests or new Career Goals. 

To provide users with insight into recent activities, the FeedCollection provides a publication that enables users to access the most recent 25 FeedCollection documents. 

What we discovered quite quickly was that under this approach, if we do not aggregate information within a document, we could easily create low-value feeds. For example, if over 25 users join the system (which is common), then the entire feed is comprised of new user additions. 

To resolve this, we implemented ways to consolidate information into individual Feed documents. This approach is complicated, as is the approach to collecting information on the client-side in order to send Feed information to the server.

An important thing to understand about the Feed mechanism is that it is entirely ephemeral: the Feed's only requirement is to represent "What's New".  Put another way: there is no reason we need to maintain any history of Feed data.

### RadGrad1's UserInteraction Collection: Supporting "High Level Behaviors"

An early implementation effort during RadGrad1, which was entirely independent of Feeds, resulted in a UserInteraction collection and a set of corresponding pages that provided analyses over this data. 

The most important goal of this collection is to support a high-level analysis in which user interactions with the system are classified into one of the following general "behaviors":

| Behavior | Description |
| -------- | -------------|
| Login | Logging in |
| Outlook |  Updating interests, career goals |
| Exploration | Viewing items in an Explorer |
| Planning | Adding or removing entries from the Degree Plan |
| Verification |  Requesting verification for a completed Opportunity |
| Review | Submitting a review of a course or opportunity |
| Level | Achieving a new level |
| Complete Plan |  Completing the degree plan | 
| Profile  | Adding or removing items from one's profile |
| Logout | Logging out |

The goal of this classification scheme is to provide actionable information regarding how the system is being used. For example, if a low percentage of users are completing their degree plan, then we need to do things to encourage this behavior.

Note that there is some redundancy among Feeds and UserInteractions: New reviews, New Verifications, and New Levels are all tracked with both mechanisms. On the other hand, each mechanism tracks certain types of information not tracked by the other. 

In contrast to Feeds, UserInteractions are not ephemeral; we want to keep this information around almost indefinitely. This is because we would like to be able to support longitudinal analyses. For example, if Plan Completion was low, and we performed an intervention, will we see that Plan Completion occurred more frequently as a result?

## The solution: A proposal for RadGrad2's implementation

Implementing the primary goals of Feeds (i.e. "What's new?") and UserInteractions (i.e. "What high-level behaviors have occurred?") can be done in a radically simpler way in RadGrad2.  This is because of two significant changes in the way information about user behavior is represented:

1. Every single Collection now maintains two timestamps: createdAt and updatedAt. This means that we no longer need to implement client-side code to track whether entities (i.e. Career Goals, Interests, Opportunities, Courses, and Users) have been created or updated. Instead, we can perform a single database query to discover "What's new?" with respect to entity creation and update.

2. Each time any page is visited by any user, if it the first time that page has been visited by that user on a given day, a Meteor Method is called to record that this page is being visited by the user. This Method is currently used only to support a "lastVisited" object in each user's profile, which is accessed by Checklist Items to ensure that the user is regularly visiting pages. However, this method's implementation can be easily extended to record UserInteraction information to support later analysis of behaviors. 

Let's now make some simplifying assumptions for RadGrad2:

  * Maintaining timestamps at the grain-size of a day (YYYY-MM-DD) is satisfactory.  This means we don't need to know, for example, the sequence with which a user visited pages in the system. 
  * We don't need to know which exact courses are added and deleted from a Degree Plan for the purpose of our behavioral analysis. We do want to know that the page was visited, and we do want to know when the Degree Plan is complete.
  * Similarly, we don't need to know exactly which Interests and Career Goals are added or subtracted from a profile. We do want to know when the user visited these Explorers. 

If we make these simplifying assumptions, then it turns out that the above two mechanisms already gather almost all of the information necessary for both Feeds and UserInteractions!  In fact, upon initial review, the only behavior that we need to instrument explicitly is when the user achieves a new Level.

### Eliminate the FeedCollection, use an in-memory object to represent "What's New"

One significant outcome from this review is that the FeedCollection is a cumbersome approach to implementing "What's New", particularly now that the Collections maintain timestamps and we have Page Visit data from the UserCollection class. 

Here's an alternative that appears much simpler to implement. Rather than subscribe to a FeedCollection to obtain "What's New" in the form of the most recent 25 documents, invoke a Meteor Method to request a data structure containing "What's New". 

That Meteor Method calls a function that accesses an in-memory data structure with a timestamp indicating when it was built. If the data structure exists and was built within the past 24 hours, then it is returned.  If the data structure is more than a day old, then it is rebuilt and returned.  

Using an in-memory data structure that is re-built when it becomes "stale" is convenient because (a) it is low overhead, the computation occurs only once a day no matter how many users request the information; and (b) we don't have to worry about managing a persistent store. If the server goes down, no worries; we just rebuild the in-memory object the next time it is requested by a user. 

### Create UserInteraction documents as part of the lastVisited Method 

Since we are already invoking a method each time any user visits a given page for the first time in a day, we can use that Method to create a UserInteraction document. That document will have a timestamp field in YYYY-MM-DD format, and then an object that contains data about all of the user interactions that occurred on that day (page visits, leveling up, plan completion, etc.)

**Comment by cammoore** [comment]
A few thoughts about the proposal.

* We don't have a way of capturing deletion. For the Outlook goal, we can detect when a user adds an interest or career goal, but we don't know if they delete the interest or career goal. The ProfileInterest/CareerGoal document is removed from the collection.
* For Planning, we'll still need some 'UserInteraction' when they drag a course or opportunity into their plan. Just recording when they visited the page doesn't tell us what happens. We could look at the CourseInstance created or updated date.
* We need to be careful about the updated dates for OpportunityInstances, when a verification request is approved the opportunity instance is updated. This doesn't mean the student did anything.
* Detecting a complete plan without 'UserInteractions' may require some sort of cron job to detect when planned ICE gets to 100. Same with leveling up.
* With the last update, we don't have any insight into the order of things. They may have visited a page several times during a day or moved an opportunity to several different terms. We only see the last 'event'. I'm not sure this is overly interesting.

I'm not sure what creating UserInteraction documents as a part of the lastVisited method means. As I understand it the lastVisited method will be called at most once a day at the beginning of a session. Anything that happens after that isn't recorded. Is it the previous 24 hours or can we even know the time period was? Are we going to run functions to detect if the student has completed their plan or leveled up in the previous time period?

**Comment by philipmjohnson** [comment]
This proposal implements a more coarse-grained approach to tracking behavior. 

First, a "session" is defined as "all pages visited during the period of a single calendar day (i.e. YYYY-MM-DD)". So, either a single day has a session, or it doesn't. The number of sessions for a given user in a given month is simply all of the days in that month in which at least one page was visited.

Second, let's look at how we will represent "behaviors". Here's an extension of the table from above, augmented with a new column to indicate how the behavior will be indicated within a session:

| Behavior | Old Approach | New Approach |
| -------- | -------------- | ---------------- |
| Login | Logging in | Any page visited on a day implies a login behavior  |
| Outlook |  Updates to interests, career goals |  **Not available.** |
| Exploration | Viewing items in an Explorer | Simply visiting the corresponding explorer page indicates an Exploration behavior. No tracking of actual adds or deletes.
| Planning | Adding or removing entries from the Degree Plan | **Not available.** |
| Verification |  Requesting verification for a completed Opportunity | Will instrument the "request verification" button |
| Review | Submitting a review of a course or opportunity | Will instrument the "submit review" button. |
| Level | Achieving a new level | Will instrument the setLevel command. |
| Complete Plan |  Completing the degree plan |  Implement via daily cron job. At system startup, builds in-memory data structure with plan state (complete, incomplete) for each user.  Runs each day at midnight. If plan state switches from incomplete to complete, then emit a UserInteraction document for that user. (There are edge cases where this will fail to detect a state change, but this approach avoids a persistent document.) |
| Profile  | Adding or removing items from one's profile | **Not available.** |
| Logout | Logging out | **Not available.** |

**Comment by philipmjohnson** [comment]
## Initial implementation of What's New:

- [] Build a cron job that runs periodically and can be controlled in a settings file. 
- [] When it runs, it uses createdAt and lastUpdated timestamps to find new/updated entities to return.
- [] Display results in the What's New pane in Community window.

## Initial implementation: UISManager and UIS

- [] Instrument system to generate UserInteraction documents upon page views
- [] Update What's new with community visits. 

## Initial implementation: behaviors

- [] Create in-memory structure to checkpoint user state once a day.
- [] Create cron job to generate UserInteraction documents when state changes appropriately.

We should be able to test all of this (at least manually) by setting the cron job run interval to a low number (or even create an admin button to kick it off?)
