### ISSUE TITLE
Implement Help Page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#484]
Please do work for this task in a branch called issue-484.

Perhaps we need a help page? Perhaps with a "?" icon in the menu bar (to save space).

The help page could have a set of embedded videos, or FAQs, etc.

**Comment by cammoore** [comment]
Are we reimplementing the HelpMessages that we ripped out of the system a few months ago?

**Comment by philipmjohnson** [comment]
No, not at all, we are **not** reimplementing HelpMessages. 

It just seems to me that if a user has questions, there should be some place to go to find an answer. The old approach clearly didn't work, which is why we deleted it.  Nobody even understood that those help panels functioned.  The reason that happened is because we "invented" a new UI for help, and no one understood it.

On the other hand, an explicit "Help" page is a known UI pattern.  Whether people will use that is also unknown.

**Comment by philipmjohnson** [comment]
Hopefully checklists take care of this.
