### ISSUE TITLE
Avoid redundant publication of user data

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#485]
Please do work for this task in a branch called issue-485.

## The problem

Currently, we publish three documents regarding the existence of a user to the client, though conceptually we only need to publish one.  In the case of Radgrad2, with almost 800 users, this means there are approximately 1600 extraneous documents we could potentially avoid publishing. (With a total of 5700 total published documents for a user, eliminating this redundancy would reduce the publication overhead by about 30%).

For each user, we define a document for them in the following three collections:

* In the Meteor.users collection
* In the Slugs collection
* In the union of the Profile collections

## The solution

It would be optimal if:

* We didn't publish all users in Meteor.users to the client.
* We didn't define a Slug for each user

And instead used the various Profile collections as our sole source of client-level info about users. 

However, this will not be totally straightforward. For example, the UserCollection uses Meteor.users for various methods. Since Meteor.users is published to the client, methods such as Users.isDefined() works fine on the client. If we stop subscribing to all users, then this method will need to be reimplemented in order to work on both server and client sides. 

For this task, investigate what changes would need to be made to avoid publishing three documents per user to the client.

**Comment by cammoore** [comment]
I'm not sure we can stop the publication of Meteor.users to the client. This is done from the accounts-base package. Nowhere in our code do we subscribe to this publication. According to the Meteor docs, https://docs.meteor.com/api/accounts.html#Meteor-users, there is a record for each registered user.

We can stop defining a slug for each user. The Meteor.user() record has a unique username. So defining a slug to ensure uniqueness is redundant.

**Comment by philipmjohnson** [comment]
Yes, I think we can stop publication of the entire Meteor.users collection.   See the following thread, which indicates that (unless autopublish is enabled), only the current user's information is sent to the client by default:

https://forums.meteor.com/t/preventing-all-meteor-users-from-being-published-to-the-client-need-to-publish-only-specific-ones/11575

The documentation for the accounts-base package confirms that only the current user's document is published to the client by default:

https://docs.meteor.com/api/accounts.html

Just intuitively, it would be a huge security hole for Meteor to always tell each client about every single registered user in the system. And what if a system has, say, 100K users? Would Meteor require each client to download a collection with 100K documents? 

I think this is where we publish the entire Meteor.users collection:

https://github.com/radgrad/radgrad2/blob/02daeea0617f10916349f75afe9974e429acfdf8/app/imports/api/user/UserCollection.ts#L463-L473

As I note above, simply deleting this publication will probably break things due to client-side dependencies on Meteor.users. The good news is that I don't think we reference Meteor.users directly in any client-side code, but instead indirectly through calls to methods on the Users class instance.  So, we can hopefully fix this within the Users class implementation.

**Comment by cammoore** [comment]
We don't create slugs for usernames.

Going to put into To Do.

**Comment by philipmjohnson** [comment]
I'm going to close this, I think it's a very low priority issue right now. We can revisit this in the future if it becomes an issue.
