### ISSUE TITLE
Provide 4 event dates per Opportunity, plus Admin/Sponsor checklist item to manage

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#491]
Please do work for this task in a branch called issue-489.

## The problem

RadGrad will be more helpful to users if Opportunities can have associated event dates. Then the system can remind users about upcoming deadlines associated with events they have added to their profile. Currently we have only one event date field, but many opportunities have more than one event data. 

## Proposed solution

Provide eight new optional fields for Opportunity documents: eventDate1, eventDateLabel1, .... eventDate4, eventDateLabel4. The date is a Date, the label is a string.

The Opportunity sponsor, or admin, can fill in one or more of these fields.  If present, they can be used to issue reminders and checklist items for students, and will appear in their Community page under "Upcoming Events".  The label field can provide more details about what the event date involves ("Application deadline", etc.).

These dates will become out-of-date over time. To keep them current, we can create a cron job that runs periodically, searches for out-of-date dates, and then create a checklist item for Advisors, Admins, and Faculty (sponsors) that informs them when there is an out-of-date Opportunity event date.

**Comment by cammoore** [comment]
This is related to #440.

**Comment by cammoore** [comment]
Added the 4 event dates and labels.
Updated the Add and Update forms.
Created OutOfDateChecklist for sponsors.
