### ISSUE TITLE
Checklist: all Interests/Career Goals have at least one Course/Opportunity, and vice-versa

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#495]
Please do work for this task in a branch called issue-495.

It will be frustrating to students if we list Interests and/or Career Goals that they cannot "pursue" through at least one Course or Opportunity.

Create a checklist item for Advisors and Admins that checks that all Interests and Career Goals are associated with at least one Course or Opportunity.

Conversely, make sure we've tagged all Courses and Opportunities with at least one Interest.

**Comment by cammoore** [comment]
Created 2 new checklists one for issues the other for career goals.
Created the AdminHomePage
Updated the AdvisorHomePage to include the two new checklists.
