### ISSUE TITLE
Upload STAR data for Shinya, Tim, Caliana, and Trey

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#500]
One of their onboarding tasks will be to use RadGrad2 to update their degree experience, so it would be useful for them to have up to date STAR data in radgrad2.ics.hawaii.edu.

It might be good to try to do this soon. Even if their data doesn't include the results from the Spring 2021 semester, that's close enough. And it would be good to find out early if we have problems doing STAR uploads. 

I checked and Trey, Caliana, and Timothy already have accounts. Shinya does not, presumably because he's a CE student? We can create an empty account for him? Or should we upload his data to the Comp Eng instance and have him use that instead? 

This might also be a good time to do a database dump from RadGrad2 and try to load the resulting fixture in a development instance in order to see if dump/restore has any obvious problems. (Do an Integrity Check after the restore.)

**Comment by cammoore** [comment]
Done.
