### ISSUE TITLE
5. Review the research

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#501]
Now that you've had some practical exposure to RadGrad as a software system, it's important to understand RadGrad as a research project.  To begin, please read the following two papers:

Philip M. Johnson, Carleton A. Moore, Peter Leong, Seungoh Paek, [DEP/RadGrad: Enhancing individualized learning plans and communities of practice to improve engagement, retention, and diversity in undergraduate computer science education](http://csdl.ics.hawaii.edu/techreports/2018/18-01/18-01.pdf), Technical Report CSDL-18-01, January 2018, University of Hawaii, Honolulu, HI.

Philip M. Johnson, Carleton A. Moore, Peter Leong, Seungoh Paek, RadGrad: [Removing the 'Extra' from Extracurricular to Improve Student Engagement, Retention, and Diversity](http://csdl.ics.hawaii.edu/techreports/2019/19-04/19-04.pdf), In Proceedings of the 51st ACM Technical Symposium on Computer Science Education (SIGCSE 2020), March 2020.

Once you've read them, please write an essay for your professional portfolio that covers the following issues:

* In your own words, what is the purpose of the RadGrad research project?
* How does RadGrad2 support the goals? What could be improved about the system this summer that would further support the goals?
* What would be the design of a pilot study this summer that would help evaluate RadGrad's project toward the goals?

When you've finished your essay and published it to your professional portfolio, please put the URL as a comment to this issue.

**Comment by saitoshi** [comment]
https://saitoshi.github.io/RadGradResponse.html

**Comment by trey-sumida** [comment]
https://treysumida.com/projects/radgrad/radgradoverview

**Comment by timothyhuo1** [comment]
https://timothyhuo1.github.io/essays/radgradresearch.html

**Comment by CalianaFortin** [comment]
https://calianafortin.github.io/essays/Reviewing-RadGrad-as-a-Research-Project.html

**Comment by ruizaj** [comment]
https://ruizaj.github.io/essays/radgrad_research.html
