### ISSUE TITLE
Make "repeatable" a property of courses

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#505]
Please do work for this task in a branch called issue-505.

Currently, the "repeatable" property of courses is defined in the settings file.  A better place to define it is as part of the Course definition.  This means:

* Define an optional property of courses called "repeatable", which defaults to false if not present.
* Update the data model UI for courses to support this field when adding or updating a course definition.
* Update the dump/restore methods to provide the repeatable property.

**Comment by cammoore** [comment]
Done.
