### ISSUE TITLE
Problems with Check Integrity

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#510]
Please do work for this task in a branch called issue-510.

I just ran the CheckIntegrity function on the uhm/ics instance. There are two issues:

1. There are 12 integrity problems, all associated with the same user and same entity.
2. The server-side integrity check does not return and get displayed in the window. 

<img width="1578" alt="Screen Shot 2021-05-17 at 11 01 23 AM" src="https://user-images.githubusercontent.com/290288/118535501-66a5f500-b6ff-11eb-80bf-4d1173bc3ff4.png">

**Comment by cammoore** [comment]
I think the checkIntegrity for opportunity instances is busted. shaziney is a very old student and may have gotten credit for opportunities before we had verification requests.

One solution is to change the checkIntegrity. Another is to create verification requests.

**Comment by philipmjohnson** [comment]
Check Integrity works fine on small datasets, so this problem appears to be due to a socket timeout.  Googling reveals that there is no simple way to increase the websocket timeout. Instead, people recommend a different design (i.e. for example, put the results into a database document and subscribe to it, so you can return immediately and use pub/sub to get the results whenever they become available.

Here's an example posting when you google on "meteor methods timeout":

https://forums.meteor.com/t/how-to-increase-meteor-call-timeout/41241

For now, it's not clear to me how to address this.  I want to think further.

**Comment by philipmjohnson** [comment]
Provided a workaround for socket timeout: the server-side results are printed to the server-side console. 

The integrity problem will be fixed when this student is matriculated.
