### ISSUE TITLE
Uncaught Error: [Invalid term: tXv8d2W6CBX5aAonq]

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#514]
Please do work for this task in a branch called issue-514.

https://app.montiapm.com/et/5aa0dcf2-18e0-4a9c-b522-98302444ad6e/svZHraoAqMKmQcpkm

**Comment by cammoore** [comment]
This was caused by assuming the drop occurred in an academic term view. Drops in other locations don't have an academic term slug as the dropID. This caused the error. 

Now check to see if the dropID is an academic term slug.
