### ISSUE TITLE
[2hbT45H3gEGnxGhSr is not a defined OpportunityInstance]

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#515]
Please do work for this task in a branch called issue-515.

https://app.montiapm.com/et/1eaeb344-0e35-4a9d-be7e-5fe2222a835f/svZHraoAqMKmQcpkm

https://app.montiapm.com/et/2c55f787-c4d2-41ad-8f31-c7133809d4bf/svZHraoAqMKmQcpkm

**Comment by cammoore** [comment]
Merging a 'fix' into master. Not sure if this is really a fix. Going to wait on Monti APM to close this issue.

**Comment by philipmjohnson** [comment]
Unfortunately, it still seems to be occurring after deployment of this fix:

https://app.montiapm.com/et/ef34aac0-03bd-4acb-b34f-1e703f1155e7/svZHraoAqMKmQcpkm

**Comment by cammoore** [comment]
The link doesn't work anymore.
I think this issue was due to the sticky state in the Degree Planner. Now that it is gone, I'm going to close this issue and see if we get this error in the future.
