### ISSUE TITLE
Uncaught Error: [Python and Django full stack web developer boot camp is not a defined Opportunity]

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#517]
Please do work for this task in a branch called issue-517.

https://app.montiapm.com/et/fbc84f23-8631-427c-a89e-ebefa4908f9a/svZHraoAqMKmQcpkm

**Comment by cammoore** [comment]
The code to strip off the type of the reviewee used indexOf. The name of the opportunity is "Python and Django full stack web developer boot cam (Udemy)". We got the wrong '('. Now using lastIndexOf.
