### ISSUE TITLE
[dRyhMX3QyZzRavjLy is not a valid instance of ProfileOpportunity.]

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#519]
Please do work for this task in a branch called issue-519.

https://app.montiapm.com/et/88bfaec5-b125-40ed-a47a-75d34b2c9382/svZHraoAqMKmQcpkm

**Comment by cammoore** [comment]
The link doesn't work anymore.
I think this issue was due to the sticky state in the Degree Planner. Now that it is gone, I'm going to close this issue and see if we get this error in the future.
