### ISSUE TITLE
Degree Planner Improvements

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#523]
Please do work for this task in a branch called issue-523.

Student review and discussion (radgrad2-chat channel, Thu May 20) has uncovered several opportunities for improvement to the Degree Planner:

* There are redundent courses in the historical degree plan. 
* There are courses listed in the "inspector" that are already completed in the degree plan.
* The representation of courses could be improved:
    * Make them larger
    * Add six dots to indicate they are draggable.
    * Have an onHover mechanism so they change display when the mouse is over them. 
    * Maybe give them more of a 3D appearance.

In addition, [Caliana's critical review](https://calianafortin.github.io/essays/A-critical-review-of-RadGrad.html#impressions-on-the-planner-page) provides additional information:

* Courses are hard to select
* Buttons go dark (button focus problem; we need to solve in Semantic UI theme)
* Page doesn't appear to be reactive; adding opportunities to profile does not update the Degree Planner inspector window
* Delete "+ Drag here" from past semesters since you can't drag courses to prior semesters. (Can we delete "Drag Here" entirely once we make it more obvious that tiles are draggable?)

**Comment by cammoore** [comment]
You can drag opportunities into past academic terms.
