### ISSUE TITLE
Add consent/non-consent buttons to Terms and Conditions page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#526]
Please do work for this task in a branch called issue-526.

Currently, the only place where a student can indicate consent to the Terms and Conditions is via the checklist. 

A more natural place to do it is directly in the Terms and Conditions page. 

We should allow consent/non-consent to be indicated in both of these places.

That means that the code to implement consent/non-consent must be refactored out of the checklist component so that it can be re-used in the Terms and Conditions page as well.

**Comment by cammoore** [comment]
We should add a `<Confirm />` component if they don't consent to the terms and conditions.
