### ISSUE TITLE
"Upcoming courses" checklist item not working correctly

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#527]
Please do work for this task in a branch called issue-527.

Courses are listed as "upcoming" which are in the past.

See [Caliana's review](https://calianafortin.github.io/essays/A-critical-review-of-RadGrad.html#courses-on-the-to-do-list) for more details.

**Comment by cammoore** [comment]
Some of the courses may have been out of date. I think I uploaded the STAR data fixes the issue with old courses.

I cannot reproduce this bug.
