### ISSUE TITLE
Courses Explorers

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#53]
Please do work for this task in a branch called issue-53.

- [x] Create Term Card
- [ ] Create individual explorer.

**Comment by gcalica** [comment]
Need to fix two minor UI bugs at a later PR
https://github.com/radgrad/radgrad2/blob/b5ee7fa6ac3bf55af2f858a229c998c337961b3e/app/imports/ui/components/student/StudentExplorerCoursesWidgetButton.tsx#L90

https://github.com/radgrad/radgrad2/blob/b5ee7fa6ac3bf55af2f858a229c998c337961b3e/app/imports/ui/components/student/StudentExplorerCoursesWidgetButton.tsx#L156
