### ISSUE TITLE
Opportunities Explorers

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#56]
Please do work for this task in a branch called issue-56.

- [x] Create Term Card
- [ ] Create individual explorer.

**Comment by gcalica** [comment]
Related to #53, TermCard has been implemented in [0fef7a07044f6](https://github.com/radgrad/radgrad2/commit/0fef7a07044f614e221fbd1e482683f317f7de18).

However, it hasn't been tested yet to see if it adds Opportunities to plan and hides them properly. This should be done once this issue is started.

**Comment by gcalica** [comment]
Need to fix two minor UI bugs at a later PR. These bugs are the same as [53#issuecomment-502328686](https://github.com/radgrad/radgrad2/issues/53#issuecomment-502328686) except it's for Opportunities Components. 

https://github.com/radgrad/radgrad2/blob/ad7510d1dbad0adfe8ab2db3a3bcfe8c7047281f/app/imports/ui/components/student/StudentExplorerOpportunitiesWidgetButton.tsx#L140-L141
