### ISSUE TITLE
Fix broken scraper: Angel List

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#565]
Please do work for this task in a branch called issue-565.

Error from April 4 scrape:

```
C:\Users\JenniferHsu\Documents\GitHub\internaloha\scraper>npm run scrapers angellist --save statistics

> scrapers@0.1.0 scrapers C:\Users\JenniferHsu\Documents\GitHub\internaloha\scraper
> node scrapers/main.js "angellist" "statistics"

Starting scraper angellist at 9:11 PM
Angellist:  Our Error:  waiting for selector `#user_email` failed: timeout 30000ms exceeded
Finished scraping!
```

**Comment by ruizaj** [comment]
Can't get passed the hCaptcha system. Even correct answers to the puzzles will not go through.

**Comment by philipmjohnson** [comment]
Hmm. Time to maybe investigate running the script from inside chrome dev tools? Although I dunno if you write out a file to the local system from there.
