### ISSUE TITLE
Users Explorers

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#57]
Please do work for this task in a branch called issue-57.

- [x] Create Student User Card
- [x] Create individual explorer.

**Comment by gcalica** [comment]
I can't find anywhere on the original radgrad where there is an individual explorer for a user. There are files called explorer-choose-user-widget.html and .js file of it, that is similar to the code of card-explorer-users-widget, but it doesn't seem like the explorer-choose-user-widget code is used anywhere.

**Comment by gcalica** [comment]
There is also a file called explore-user-widget.html but this seems to be the same exact code as student-user-card. 

However, it seems like explore-user-widget is deprecated and is the older version of student-user-card.

However, student-user-card is what's used in the CARD Explorer for Users. I still can't find any trace of any files that render an individual explorer for a user, if there's even any in the first place.

**Comment by gbarcelo** [comment]
Refactored StudentUserCard to UserProfileCard to reflect generic nature

**Comment by gbarcelo** [comment]
Implemented placeholder ExplorerUsersWidget (tried to follow naming observed convention). Also started getting used to documentation format, so just look at Quick Documentation (default hotkey F1) for details on usage without having to open up source code
