### ISSUE TITLE
Ensure that publications with user-level info return data only to logged in users

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#581]
Please do work for this task in a branch called issue-581.

Update the publish methods for user-level collections to check that there is a logged in user. If not, then return an empty array. 

For example:

```
Meteor.publish (collection, () => {
  if (!Meteor.user()) {
    return [];
  }
  
  (rest of publication code goes here)

});
```

While we are at it, make sure that publications always return an empty array or a cursor. Otherwise they will hang.

**Comment by cammoore** [comment]
What are user-level collections?
