### ISSUE TITLE
Admin and Student students participating by semester is empty

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#587]
Please do work for this task in a branch called issue-587.

<img width="1423" alt="Screen Shot 2021-06-03 at 9 30 55 AM" src="https://user-images.githubusercontent.com/1194643/120701343-6f603000-c44e-11eb-96ff-09bdc5f84802.png">

In both the CourseViewPage and the OpportunityViewPage.

**Comment by timothyhuo1** [comment]
Students Participating By Semester seems to be working on the current master branch. 
<img width="1341" alt="Screen Shot 2021-06-04 at 9 01 37 AM" src="https://user-images.githubusercontent.com/61216890/120850720-83219a00-c513-11eb-9a6e-f1276d8eada0.png">
