### ISSUE TITLE
Create a new development fixture

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#597]
Please do work for this task in a branch called issue-597.

The description fields for all Career Goals and Interests have been edited to support our new summary format (use the first sentence of the description as the summary).

It would be nice for the development fixture to provide these summaries so that it provides a more realistic development experience. 

To do this task, you must:

1. Obtain a snapshot of the production database from Philip or Cam containing the updated descriptions.
2. Run Cam's script to generate a new development fixture.

**Comment by cammoore** [comment]
There is one gotcha in creating a new fixture from the live data on radgrad2.ics.hawaii.edu. johnson@hawaii.edu is an advisor on the live data, but our testcafe test use johnson@hawaii.edu to test the faculty pages. 

There are two possible fixes:

 1. Manually move johnson@hawaii.edu from the AdvisorProfileCollection in the downloaded fixture.
 2. Change the faculty member in the testcafe tests.

**Comment by philipmjohnson** [comment]
There is also an option (3), which I like the best:

3. Define all users (Students, Advisors, Faculty, and Admin) as part of the test fixture config file; don't use any users from the live data. This is better from a privacy standpoint; we can use fake names for all users.
