### ISSUE TITLE
Problem after retiring a course in the Admin Course Explorer

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#656]
Please do work for this task in a branch called issue-656.

After retiring a course from the Admin Course Explorer, the next course in the list no longer displays, and instead generates an error regarding a missing slug:

https://app.montiapm.com/apps/svZHraoAqMKmQcpkm/errors/overview?range=3600000&date=1623875874687&selection=3a38c1d4fb9ab072d61cde69dc045988

This is super weird. It has happened twice to me in radgrad2.  Now, trying to go to the following browser detail pages are broken:

https://radgrad2.ics.hawaii.edu/#/admin/radgrad@hawaii.edu/explorer/courses/ics_624
https://radgrad2.ics.hawaii.edu/#/admin/radgrad@hawaii.edu/explorer/courses/ics_667

I won't retire any more courses until we figure out what's going on!

**Comment by philipmjohnson** [comment]
Approach:

* When processing prereqs, check for slugs that are comma concatenations, and flatten them into an array.
* Filter out any prereqs that are retired. 
* Add "Potential" to the Prerequisite UI component title string to make it clear that this is not a binding situation.

**Comment by cammoore** [comment]
The UpdateCourseForm has the same issue with prerequisites.
