### ISSUE TITLE
Fix Broken Scraper: ACM

### ISSUE THREAD

**Issue by ruizaj** [radgrad/radgrad2#668]
Please do work for this task in a branch called issue-668. Similar problem with Indeed where runs perfectly on dev open, but not in production mode. Attempt fixes to run unattended or determine if needed to add to the attended list.

**Comment by timothyhuo1** [comment]
Running acm scraper on prod closed seems to be working. Also, acm scraper works when running all scrapers that support unattended mode. 
![Screen Shot 2021-06-21 at 4 13 29 PM](https://user-images.githubusercontent.com/61216890/122852190-e9484400-d2ab-11eb-9fbb-6cb845f31366.png)
