### ISSUE TITLE
Change Calendar component to set only date, not date and time

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#682]
Please do work for this task in a branch called issue-682.

When editing Opportunities, there is a pop-up calendar component. This component currently requires you to set both the date and the time.  This form currently appears to use the built-in Uniforms DateField component.

It would be better if we displayed only the date and not the time. So: investigate replacing the built-in component with another one that can be configured to only display dates and not times. We already use react-datepicker in AdminAnalyticsBehaviorTablePage.tsx which does exactly what we want. However, that page does not use Uniforms.  What we want to do is use Uniforms, and use react-datepicker.  According to [this comment](https://gitter.im/vazco/uniforms?at=59821b1b614889d475122230) it combines seamlessly.

**Comment by cammoore** [comment]
Closed via #666.
