### ISSUE TITLE
Improve Matriculate Students functionality

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#686]
Please do work for this task in a branch called issue-686.

## 1. Fix React Warning

Clicking on the Matriculate Students tab results in a React warning in the console:

<img width="1308" alt="Screen Shot 2021-06-27 at 12 00 47 PM" src="https://user-images.githubusercontent.com/290288/123560693-876e5b00-d73f-11eb-9611-4a8b603be897.png">

## 2. Provide feedback when matriculation process finished

Upon completion of matriculation method, provide a summary of results:

* How many students moved to alumni
* How many moved to retired.
* How many retired.
* (Maybe) Note that a zip file is downloaded with matriculated student info.

## 3. Update Integrity Check

After matriculation, Integrity Check (server side) can fail because users are no longer defined in UserInteraction collection.

Solution: don't do integrity check on UserInteraction for defined users. We will have to be cognizant that user interaction analyses on very old data might encounter undefined students.

**Comment by cammoore** [comment]
<img width="1307" alt="Screen Shot 2021-06-30 at 1 50 58 PM" src="https://user-images.githubusercontent.com/1194643/124044933-4168ff80-d9aa-11eb-8e02-01729e1b83c4.png">

Done with all three.
