### ISSUE TITLE
Add a few internships to the development fixture.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#703]
Please do work for this task in a branch called issue-703.
This is a temporary fix so we can start working on Internships in RadGrad.

* [x] Add a few, at least 5, internships to the development fixture. They should come from the InternAloha data files.
* [ ] Implement the Landing Internship explorers.
* [ ] Implement the logged-in Internship explorers.

**Comment by philipmjohnson** [comment]
I suggest that Cam do this because the change has to be made to the config file for fixture generation, not directly to the fixture file.

**Comment by cammoore** [comment]
I'm not going to do the explorers at this time. Will create more issues for the different UI components.
