### ISSUE TITLE
Check Scraper: Simply Hired

### ISSUE THREAD

**Issue by ruizaj** [radgrad/radgrad2#734]
Please do work for this task in a branch called issue-734. Simply Hired's amount of listings dropped considerably on scrape. Rerun scraper and check if there's any significant problems causing this.

**Comment by timothyhuo1** [comment]
Simply Hired scraper seems to have no problem. Ran the scraper twice:

<img width="972" alt="first try" src="https://user-images.githubusercontent.com/61216890/126204225-9c4ff48e-3e02-40b4-b011-e8e12477e119.png">

<img width="539" alt="second try" src="https://user-images.githubusercontent.com/61216890/126204235-add8e408-1b58-4c0e-8c01-9094e5c3aaa8.png">
