### ISSUE TITLE
Remove Prerequisites

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#741]
Please do work for this task in a branch called issue-741.

Review by faculty and advisors led to the conclusion that we should remove prerequisites from the system. 

This is a non-trivial task, and involves at least the following:
  
 * Removing the UI components that display prerequisites.
 * Removing the prereq fields from courses.
 * Removing prereqs data from the database.
 * Removing prereqs from the development fixture script. 
 * Migrating the production system to one that doesn't involve prerequisites.
 * Making sure tests are OK.

**Comment by cammoore** [comment]
Migrating the production system to one that doesn't involve prerequisites might be as simple as:

1. Deploying the new code.
2. Dump the database this won't have corequisites or prerequisites.
3. Reset the db.
4. Load the new data dump.
