### ISSUE TITLE
Differentiate color of courses and opportunities in Degree Planner

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#743]
Please do work for this task in a branch called issue-743.

The Degree Planner would be easier to understand if courses and opportunities had different colors. 

Right now all of the tiles are "teal". 

The current RadGrad color palette is here: https://www.radgrad.org/docs/developers/patterns/colors#the-palette

I am wondering if maybe "Green" and "Blue" would be a complementary pair?  Or "Green2" and "Blue2" if a darker color is needed to contrast better with the text?

**Comment by cammoore** [comment]
Using the myICE colors.
