### ISSUE TITLE
Test RadGrad against CAS 6.3

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#751]
Please do work for this task in a branch called issue-751.

Please see this email:

<hr/>

Hello all,

Please be advised that CAS will be upgraded from version 5.0 to version 6.3, the latest supported version.  It is important that you test your applications against the new version of CAS as soon as possible.

Schedule:

New 6.3 Test environment: now available
https://cas-future-test.its.hawaii.edu/cas/

Production environment upgrade: Sunday, August 15, 6:45 AM, 2021

It is important that you review the blog for the details, including details on the one known issue:
   o Blog: https://www.hawaii.edu/bwiki/display/UHIAM/2021/07/09/CAS+6.3+Upgrade+plans+for+Summer+2021

Please review the blog.  Ask questions on this list or contact IAM at <its-iam-help@hawaii.edu>.

<hr/>

**Comment by cammoore** [comment]
I've updated cammoo:accounts-cas to support CAS protocol 2.0. 

Now need to fix the redirect problem that has popped up.

**Comment by cammoore** [comment]
Turns out that the cammoo:accounts-cas was not calling the callback function in `Meteor.loginWithCas(callback)`. Fixed that problem.

We can't merge this into master until the change to 6.3.

**Comment by cammoore** [comment]
The CAS production environment will be upgraded Sunday, August 15, 6:45 AM, 2021.
So we can switch over Sunday.
