### ISSUE TITLE
radgrad2.ics.hawaii.edu with updated CAS doesn't seem to work.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#756]
Please do work for this task in a branch called issue-753.

I have updated the .deploy-ics files and redeployed radgrad2. After attempting to login, I go through the UH CAS stuff normally and successfully, but then don't get to the home page. Instead, I get here:

<img width="797" alt="Screen Shot 2021-08-17 at 11 10 30 AM" src="https://user-images.githubusercontent.com/290288/129801333-f0371be1-7012-492a-a7d7-788ed2d16499.png">

Ideas?

**Comment by philipmjohnson** [comment]
HOld on a second, I think I didn't install cammoo:accounts-cas?

**Comment by philipmjohnson** [comment]
Here's the stacktrace from MontiAPM.  I tried to login as a faculty member. Perhaps Cammoo's accounts package can't handle whatever faculty records return?

```
message: Cannot read property '0' of undefined
stack:
TypeError: Cannot read property '0' of undefined
    at packages/cammoo_accounts-cas.js:103:115
    at Parser.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/cammoo_accounts-cas/node_modules/xml2js/lib/xml2js.js:489:18)
    at Parser.emit (events.js:375:28)
    at Parser.emit (domain.js:470:12)
```

**Comment by cammoore** [comment]
Fixed
