### ISSUE TITLE
Change ICE points for a "B" from 6 to 8 points

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#769]
Please do work for this task in a branch called issue-769.

In IceProcessor.ts, line 45, change the number of points for a B from 6 to 8. 

Hopefully this reduces the number of courses that need to be added to ones degree plan to "complete it" from 17 to 13. This is a more manageable number. 

I don't know if changing this constant in this file has unexpected consequences, so I am asking Cam to do it since he's more familiar with ICE Processing.

**Comment by cammoore** [comment]
This is related to #779
