### ISSUE TITLE
radgrad2.ics.hawaii.edu opportunity explorer broken for admin

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#773]
Please do work for this task in a branch called issue-773.

Login to radgrad2.ics.hawaii.edu as admin, and attempt to retrieve opportunity explorer. You get this:

<img width="1608" alt="Screen Shot 2021-09-09 at 7 00 07 AM" src="https://user-images.githubusercontent.com/290288/132731365-6c143e33-49cf-423d-9c6d-2b7306b03a12.png">

And there will be a MontiAPM error generated. 

I have been seeing these errors for the past couple of days. I think this might have something to do with Henri having deleted an Opportunity recently. 

It is interesting to note that if I login as myself (johnson), I do not get this error and the explorer displays OK.

**Comment by cammoore** [comment]
The issue was that when an Opportunity is removed, we don't remove any ProfileOpportunities associated with the Opportunity. This is probably true for career goals, courses, and interests.
