### ISSUE TITLE
Update checkIntegrity for profile collections

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#775]
Please do work for this task in a branch called issue-775.

It appears that check integrity does not flag opportunities in the profile that have subsequently been deleted. Fix this so running the integrity check reveals this problem.

**Comment by cammoore** [comment]
Do you mean retired or deleted?

**Comment by philipmjohnson** [comment]
Hmm. I think deleted?  It's not an integrity violation to link to a retired opportunity, I think, because that's why we have the "retired" flag (i.e. it won't be presented to new users, but existing links to it are valid.)

Does that make sense?

**Comment by cammoore** [comment]
Duplicate. Already fixed.
