### ISSUE TITLE
Fix bug in image uploading

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#800]
Please do work for this task in a branch called issue-800.

The image upload process doesn't appear to be working right.

To fix this:

* Create a settings.development.json file in the custom directory. This file can contain the Cloudinary credentials because it is git-ignored.
* Use `meteor npm run start-custom` to bring up a development server with the cloudinary credentials.
* Diagnose the problem and fix it.

**Comment by cammoore** [comment]
The issue was in the PictureField code. When cloudinary returned the URL to the image, we didn't call onChange to set the AutoForm's value in the model.
