### ISSUE TITLE
Fix bug that displays an internship in Explorer but can't find the document for details view

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#806]
Please do work for this task in a branch called issue-806.

In some cases, an internship appears in the Explorer window but when clicking "get details", no details on this listing can be retrieved. 

Please fix this bug.

**Comment by cammoore** [comment]
I can't reproduce this bug.

**Comment by cammoore** [comment]
I was wrong. The issue is students don't subscribe to all the internships, but admin does.
