### ISSUE TITLE
Admin user can't go to manage opportunities page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#815]
Please do work for this task in a branch called issue-815.

The admin user has a checklist item about opportunities they sponsor:

<img width="521" alt="Screen Shot 2022-02-17 at 8 45 49 AM" src="https://user-images.githubusercontent.com/290288/154549759-db7eb1ff-9296-422d-be2c-3c8199807cd1.png">

Unfortunately clicking the link takes them to a page not found.

**Comment by cammoore** [comment]
Admins shouldn't sponsor opportunities. I removed the checklist from the HomePage.
