### ISSUE TITLE
Add a count of unique users to Behavior Table page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/radgrad2#818]
Please do work for this task in a branch called issue-818.

The "Behavior Table" Page in admin mode provides "counts" of the number of instances of a given behavior, as well as an enumerated list of the "unique users" exhibiting that behavior. 

For analyzing RadGrad usage, it would be very helpful to provide the "count" of unique users in addition to the list. That way you don't have to count them by hand. (And there are hundreds when you analyze across an entire year.)

In addition, please sort the list of users alphabetically by last name before presenting them in the table.

**Comment by cammoore** [comment]
Done.
