### ISSUE TITLE
Reduce the number of terms shown in the Course Scoreboard.

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#88]
Please do work for this task in a branch called issue-88.

The data in the Course Scoreboard is only good for about 3 years. We should only show three years of data.

* [x] Reduce the number of terms to only show the future 3 years.
* [x] Add an Export to CSV button and functionality.

**Comment by gcalica** [comment]
The work for this branch was done in #37. This was mainly because the first task was just a few lines to implement. And #37 already implemented task 2.
