### ISSUE TITLE
General UI issues

### ISSUE THREAD

**Issue by cammoore** [radgrad/radgrad2#94]
This issue is for recording UI issues in RadGrad2. We won't be creating a branch for this issue just recording the issues and fixes.

When you find a UI issue add a comment to this issue with a checkbox.

Periodically check back to this issue and if you want to fix a UI issue, use your own branch. When it is fixed check the checkbox in this issue.

- [x] https://github.com/radgrad/radgrad2/issues/94#issuecomment-506043033
- [x] https://github.com/radgrad/radgrad2/issues/94#issuecomment-506073326
- [x] https://github.com/radgrad/radgrad2/issues/94#issuecomment-506529088
- [ ] https://github.com/radgrad/radgrad2/issues/94#issuecomment-508634593
- [x] https://github.com/radgrad/radgrad2/issues/94#issuecomment-508984058
- [ ] https://github.com/radgrad/radgrad2/issues/94#issuecomment-509125416
- [ ] https://github.com/radgrad/radgrad2/issues/94#issuecomment-511618908
- [x] https://github.com/radgrad/radgrad2/issues/94#issuecomment-511629599
- [x] https://github.com/radgrad/radgrad2/issues/94#issuecomment-512638583
- [ ] https://github.com/radgrad/radgrad2/issues/94#issuecomment-512977108
- [ ] https://github.com/radgrad/radgrad2/issues/94#issuecomment-520088459

**Comment by gcalica** [comment]
- [ ] https://github.com/radgrad/radgrad2/issues/53#issuecomment-502328686
- [ ] https://github.com/radgrad/radgrad2/issues/56#issuecomment-502344785

**Comment by gcalica** [comment]
- [ ] StudentHomeMenu seems to have been placed all the way to the middle of the StudentHomePage. I suspect that HelpPanelWidget may have broken this because it was fine before but maybe not.

**Comment by gcalica** [comment]
- [ ] All the background color of pages are white. <Menu> from React Semantic has a gray color background which makes everything ugly.

**Comment by gcalica** [comment]
- [ ] Individual Explorer Career Goals Page isn't reactive (profile pictures)

**Comment by gcalica** [comment]
- [ ] The Dropdown for "Name" overflows. [https://imgur.com/a/ZRZ3WkS](https://imgur.com/a/ZRZ3WkS)

**Comment by gcalica** [comment]
- [ ] There is some weird logic behavior where after you add a new Academic Year instance by clicking on the "Add Academic Year" button, clicking on either "Next Year" or "Previous Year" will render the Degree Planner to only have 2 or 3 year columns. However clicking on "Next Year" or "Previous Year" again fixes it back to normal.

**Comment by cammoore** [comment]
* [ ] Add interest list and sort the Career Goals based upon interest match. See RadGrad 1 vs 2 Career Goals explorer.

**Comment by gcalica** [comment]
- [ ] RadGradMenuProfile isn't reactive to profile picture changes and ICE changes

**Comment by gcalica** [comment]
- [ ] The three buttons (View More, Add to Plan, Hide) for Courses and Opportunities Widget in Student Home Page is not formatted properly.

**Comment by mercedezcastro** [comment]
* Student Degree Planner Page
- [ ] Courses shows up weird when added from Explorer (Adding from side panel works fine). [See here](https://imgur.com/a/Zehvpg0)
- [ ] Academic Plans Tabbed Inspector : Year dropdown can’t select other years.

* Mentor Space Page
- [ ]  Mentor name links in questions accordion don’t link to correct place.

**Comment by gcalica** [comment]
- [ ] When viewing Individual Opportunities in the Explorers, the "Semesters" list can get too big for opportunities that have been up and continuining for a while (https://imgur.com/a/fjhUJUK). We should only show the Semesters list for the current semester and future semesters.
- [ ] On top of this, need to change the "Semesters" to "Academic Terms"

**Comment by gcalica** [comment]
Closing this issue in favor of creating separate issues for UI problems for the pages and separate issues for bugs found in those pages.
